#compdef bop
# Generated by scripts/generate_completions.py; do not edit.
# zsh completion for bop (Bookmark Organizer Pro)
# Copy to a directory in your $fpath, e.g. ~/.zfunc/

_bop() {
    local -a commands=(
        'list:List bookmarks (optionally filter by category)'
        'add:Add a new bookmark'
        'delete:Delete a bookmark by ID'
        'search:Search bookmarks'
        'import:Import bookmarks from a file or a folder of exports'
        'migration:Preflight or apply a competitor export'
        'export:Export bookmarks to file'
        'categories:List all categories'
        'tags:List all tags'
        'stats:Show statistics'
        'check:Check for broken links'
        'help:Show help message'
        'ai-audit:Inspect AI audit log'
        'ingest:Extract text + reading time + language'
        'transcript:Opt-in fetch or remove a YouTube transcript'
        'structured:Show structured metadata for a bookmark'
        'snapshot:Capture a verified offline snapshot'
        'embed:Build/update vector embeddings'
        'semantic:Vector-only semantic search'
        'hybrid:Hybrid keyword + semantic (RRF) search'
        'summarize:AI summary with inline citations'
        'chat:Conversational REPL over your collection (RAG)'
        'ask:One-shot RAG question'
        'lint-tags:Detect tag duplicates / casing drift'
        'dups:Layered duplicate detector'
        'scan:Dead-link scan'
        'digest:On-this-day + rediscover + read-later view'
        'flow:Manage research-trail flows'
        'feed:Manage RSS/Atom feeds'
        'jobs:Inspect and manage local capture/index jobs'
        'imports:Inspect, retry, cancel, or roll back import sessions'
        'import-pocket:Import Pocket export (HTML or JSON)'
        'import-firefox-backup:Import Firefox bookmarkbackups JSON'
        'import-readwise:Import Readwise Reader CSV'
        'import-pinboard:Import Pinboard JSON export'
        'import-instapaper:Import Instapaper CSV export'
        'import-reddit:Import Reddit saved.json'
        'import-matter:Import Matter export CSV'
        'import-zotero:Import Zotero RDF export'
        'import-wallabag:Import Wallabag JSON export'
        'import-arc:Import Arc Browser StorableSidebar.json'
        'import-omnivore:Import an Omnivore export (zip, folder, or metadata JSON)'
        'import-csv:Import any CSV export with a URL column'
        'import-browser:Import bookmarks from Chrome/Firefox/Edge/Brave profiles'
        'zip-export:Per-bookmark or whole-collection ZIP export'
        'obsidian-export:Export to Obsidian vault'
        'epub-export:Export bookmarks as EPUB'
        'atom-export:Export Atom feed'
        'json-feed:Export JSON Feed'
        'opds-export:Export OPDS 1.2 acquisition feed'
        'opds2-export:Export OPDS 2.0 JSON-LD acquisition feed'
        'graph-export:Export bookmark relationship graph JSON'
        'zotero-export:Export as Zotero RDF'
        'encrypt:Encrypt a JSON file with AES-256-GCM'
        'decrypt:Decrypt an encrypted JSON file'
        'read-later:Manage read-later queue'
        'reader:Manage reader highlights/notes'
        'api-server:Run the local HTTP API'
        'mcp-server:Run the MCP server (stdio)'
        'mcp-http-server:Run the MCP Streamable HTTP server'
        'sqlite-migrate:Copy JSON bookmarks into SQLite DB'
        'recovery-bundle:Create or restore a full-library backup'
        'updates:Manage update policy'
        'smart-collections:Manage smart collections'
        'rules:Preview and apply declarative organization rules'
        'nl-query:Natural language query'
        '-h:show this help message and exit'
        '--help:show this help message and exit'
        '--version:show program'"'"'s version number and exit'
        '-V:show program'"'"'s version number and exit'
    )
    if (( CURRENT == 2 )); then
        _describe 'command or option' commands
        return
    fi

    case "$words[2]" in
        list)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--all[Show all bookmarks]'
            return
            ;;
        add)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        delete)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--force[Skip confirmation]' \
                '-y[Skip confirmation]' \
                '--yes[Skip confirmation]'
            return
            ;;
        search)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--dry-run[For a directory, show the batch plan without importing]'
            return
            ;;
        migration)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            preflight
                            apply
                        )
                        _describe 'argument' values
                        return
                        ;;
                    3)
                        local -a values=(
                            linkwarden
                            karakeep
                            raindrop
                            readwise
                        )
                        _describe 'argument' values
                        return
                        ;;
                    4)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--report[Optional JSON report output path]:report:_files'
            return
            ;;
        export)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        categories)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        tags)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        stats)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        check)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        help)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        ai-audit)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--min-confidence[Ignore AI categories below this (default 0.7)]:min_confidence:' \
                '--min-support[Require >= N confident samples per domain (default 2)]:min_support:' \
                '--json[Print the full machine-readable JSON report]' \
                '--out[Write the full JSON report to FILE]:out:_files'
            return
            ;;
        ingest)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--templates[Optional JSON/YAML structured extraction templates]:templates:_files'
            return
            ;;
        transcript)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--lang[Subtitle language, such as en or pt-BR]:lang:' \
                '--language[Subtitle language, such as en or pt-BR]:lang:' \
                '--timeout[Provider timeout in seconds (1-300)]:timeout:' \
                '--remove[Remove the stored transcript]' \
                '--json[Print machine-readable result]'
            return
            ;;
        structured)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--json[Print raw JSON payload]'
            return
            ;;
        snapshot)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        embed)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--model[Embedding model name or key]:model:'
            return
            ;;
        semantic)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        hybrid)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        summarize)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        chat)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        ask)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        lint-tags)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--apply[Apply merge fixes]'
            return
            ;;
        dups)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        scan)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--hours[Only scan unchecked for N hours]:hours:'
            return
            ;;
        digest)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        flow)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            list
                            new
                            add
                            show
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        feed)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            list
                            add
                            remove
                            fetch
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        jobs)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            health
                            list
                            retry
                            clear
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--type[Filter by job type]:job_type:' \
                '--outcome[]:outcome:(running success failure cancelled)' \
                '--retryable[Show retryable jobs only]' \
                '--limit[]:limit:' \
                '--json[]'
            return
            ;;
        imports)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            list
                            show
                            retry
                            cancel
                            rollback
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--limit[]:limit:' \
                '--json[]'
            return
            ;;
        import-pocket)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-firefox-backup)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-readwise)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-pinboard)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-instapaper)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-reddit)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-matter)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-zotero)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-wallabag)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-arc)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-omnivore)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        import-csv)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--map[Override a column mapping, e.g. --map url=Address (repeatable)]:map:' \
                '--show-columns[Print the header row and the detected mapping, then exit]'
            return
            ;;
        import-browser)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            chrome
                            firefox
                            edge
                            brave
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--profile[Profile name (default: Default)]:profile:_files'
            return
            ;;
        zip-export)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    3)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        obsidian-export)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--tag[Filter by tag]:tag:' \
                '--category[Filter by category]:category:' \
                '--since[Filter by date]:since:'
            return
            ;;
        epub-export)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--title[EPUB title]:title:' \
                '--output[Output path]:output:_files' \
                '--tag[Filter by tag]:tag:'
            return
            ;;
        atom-export)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--title[Feed title]:title:' \
                '--output[Output path]:output:_files' \
                '--tag[Filter by tag]:tag:'
            return
            ;;
        json-feed)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--title[Feed title]:title:' \
                '--output[Output path]:output:_files' \
                '--tag[Filter by tag]:tag:'
            return
            ;;
        opds-export)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--title[Feed title]:title:' \
                '--output[Output path]:output:_files' \
                '--tag[Filter by tag]:tag:' \
                '--catalog-url[Catalog URL]:catalog_url:'
            return
            ;;
        opds2-export)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--title[Feed title]:title:' \
                '--output[Output path]:output:_files' \
                '--tag[Filter by tag]:tag:' \
                '--catalog-url[Catalog URL]:catalog_url:'
            return
            ;;
        graph-export)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--output[Output path]:output:_files' \
                '--limit[Max bookmarks (default 300)]:limit:'
            return
            ;;
        zotero-export)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        encrypt)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    3)
                        _files
                        return
                        ;;
                    4)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--no-recovery[Skip recovery key generation]'
            return
            ;;
        decrypt)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    3)
                        _files
                        return
                        ;;
                    4)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--recovery-key[Decrypt using recovery key instead of passphrase]:recovery_key:'
            return
            ;;
        read-later)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            add
                            next
                            done
                            list
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        reader)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            list
                            add
                            note
                            delete
                            due
                            review
                            export
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--color[Filter color, or highlight color for add (default: yellow for add)]:color:(yellow green blue pink)' \
                '--note[Note text]:note:' \
                '--text[Filter selected highlight text]:text:' \
                '--note-filter[Filter highlight notes]:note_filter:' \
                '--tag[Filter highlight tags]:tag:' \
                '--bookmark-id[Filter the global workspace by bookmark ID]:bookmark_id:' \
                '--review[Filter review state]:review:(all new due scheduled reviewed)' \
                '--anchor[Filter anchor state]:anchor:(all anchored reanchored orphaned unverified)' \
                '--limit[Global workspace page size]:limit:' \
                '--offset[Global workspace page offset]:offset:' \
                '--output[Export output directory]:output:_files' \
                '--format[Reader export format (default: markdown)]:format:(markdown csv json)' \
                '--template[JSON annotation export template]:template:_files' \
                '--changed-since[Only export highlights modified at/after ISO timestamp]:changed_since:'
            return
            ;;
        api-server)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--port[Port number (default 8765)]:port:'
            return
            ;;
        mcp-server)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
        mcp-http-server)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--host[Host (default 127.0.0.1)]:host:' \
                '--port[Port (default 8766)]:port:' \
                '--path[Endpoint path (default /mcp)]:path:_files'
            return
            ;;
        sqlite-migrate)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--source[Source JSON file]:source:_files' \
                '--dest[Destination SQLite DB]:dest:_files'
            return
            ;;
        recovery-bundle)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            create
                            validate
                            restore
                        )
                        _describe 'argument' values
                        return
                        ;;
                    3)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--apply[Apply a verified restore (restore is validation-only by default)]'
            return
            ;;
        updates)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            status
                            check
                            configure
                            download
                            staged
                            clean-staged
                            plan
                            apply
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--dry-run[Preflight check only]' \
                '--preflight[Preflight check only]' \
                '--enable[Enable updates]' \
                '--disable[Disable updates]' \
                '--metadata-url[Metadata URL]:metadata_url:' \
                '--targets-url[Targets URL]:targets_url:' \
                '--channel[Update channel]:channel:' \
                '--allow-prerelease[Allow prerelease]' \
                '--no-prerelease[Disallow prerelease]'
            return
            ;;
        smart-collections)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            list
                            eval
                            create
                            update
                        )
                        _describe 'argument' values
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--name[Replacement name for update]:name:' \
                '--icon[Collection icon]:icon:' \
                '--tags[Comma-separated tags]:tags:' \
                '--categories[Comma-separated categories]:categories:' \
                '--domains[Comma-separated exact domains]:domains:' \
                '--content-types[Comma-separated content types]:content_types:' \
                '--keywords[Comma-separated keywords]:keywords:' \
                '--after[ISO-8601 lower date bound]:after:' \
                '--before[ISO-8601 upper date bound]:before:' \
                '--read-later-only[]' \
                '--no-read-later-only[]' \
                '--has-snapshot[]' \
                '--no-has-snapshot[]' \
                '--reader-state[Filter by persisted reader state]:reader_state:(unread in_progress finished)'
            return
            ;;
        rules)
            if [[ "$words[CURRENT]" != -* ]]; then
                case $CURRENT in
                    2)
                        local -a values=(
                            list
                            preview
                            apply
                            undo
                            import
                            export
                            enable
                            disable
                        )
                        _describe 'argument' values
                        return
                        ;;
                    3)
                        _files
                        return
                        ;;
                esac
            fi
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]' \
                '--replace[Replace existing rules during import]' \
                '--json[Print machine-readable output]'
            return
            ;;
        nl-query)
            _arguments -s \
                '-h[show this help message and exit]' \
                '--help[show this help message and exit]'
            return
            ;;
    esac
}

_bop "$@"
