# Generated by scripts/generate_completions.py; do not edit.
# fish completion for bop (Bookmark Organizer Pro)
# Copy to ~/.config/fish/completions/bop.fish

set -l commands \
    "list" \
    "add" \
    "delete" \
    "trash" \
    "search" \
    "import" \
    "migration" \
    "export" \
    "categories" \
    "tags" \
    "stats" \
    "check" \
    "help" \
    "ai-audit" \
    "ingest" \
    "transcript" \
    "structured" \
    "snapshot" \
    "embed" \
    "semantic" \
    "hybrid" \
    "summarize" \
    "chat" \
    "ask" \
    "lint-tags" \
    "dups" \
    "scan" \
    "digest" \
    "flow" \
    "feed" \
    "jobs" \
    "imports" \
    "import-pocket" \
    "import-firefox-backup" \
    "import-readwise" \
    "import-pinboard" \
    "import-instapaper" \
    "import-reddit" \
    "import-matter" \
    "import-zotero" \
    "import-wallabag" \
    "import-arc" \
    "import-omnivore" \
    "import-csv" \
    "import-browser" \
    "zip-export" \
    "obsidian-export" \
    "epub-export" \
    "atom-export" \
    "json-feed" \
    "opds-export" \
    "opds2-export" \
    "graph-export" \
    "zotero-export" \
    "encrypt" \
    "decrypt" \
    "read-later" \
    "reader" \
    "api-server" \
    "mcp-server" \
    "mcp-http-server" \
    "sqlite-migrate" \
    "recovery-bundle" \
    "updates" \
    "smart-collections" \
    "repairs" \
    "rules" \
    "nl-query"

complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "list" -d "List bookmarks (optionally filter by category)"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "add" -d "Add a new bookmark"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "delete" -d "Move a bookmark to Trash by ID"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "trash" -d "List, restore, or permanently purge Trash"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "search" -d "Search bookmarks"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import" -d "Import bookmarks from a file or a folder of exports"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "migration" -d "Preflight or apply a competitor export"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "export" -d "Export bookmarks to file"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "categories" -d "List all categories"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "tags" -d "List all tags"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "stats" -d "Show statistics"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "check" -d "Check for broken links"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "help" -d "Show help message"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "ai-audit" -d "Inspect AI audit log"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "ingest" -d "Extract text + reading time + language"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "transcript" -d "Opt-in fetch or remove a YouTube transcript"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "structured" -d "Show structured metadata for a bookmark"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "snapshot" -d "Capture a verified offline snapshot"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "embed" -d "Build/update vector embeddings"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "semantic" -d "Vector-only semantic search"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "hybrid" -d "Hybrid keyword + semantic (RRF) search"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "summarize" -d "AI summary with inline citations"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "chat" -d "Conversational REPL over your collection (RAG)"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "ask" -d "One-shot RAG question"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "lint-tags" -d "Detect tag duplicates / casing drift"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "dups" -d "Layered duplicate detector"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "scan" -d "Dead-link scan"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "digest" -d "On-this-day + rediscover + read-later view"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "flow" -d "Manage research-trail flows"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "feed" -d "Manage RSS/Atom feeds"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "jobs" -d "Inspect and manage local capture/index jobs"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "imports" -d "Inspect, retry, cancel, or roll back import sessions"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-pocket" -d "Import Pocket export (HTML or JSON)"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-firefox-backup" -d "Import Firefox bookmarkbackups JSON"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-readwise" -d "Import Readwise Reader CSV"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-pinboard" -d "Import Pinboard JSON export"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-instapaper" -d "Import Instapaper CSV export"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-reddit" -d "Import Reddit saved.json"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-matter" -d "Import Matter export CSV"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-zotero" -d "Import Zotero RDF export"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-wallabag" -d "Import Wallabag JSON export"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-arc" -d "Import Arc Browser StorableSidebar.json"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-omnivore" -d "Import an Omnivore export (zip, folder, or metadata JSON)"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-csv" -d "Import any CSV export with a URL column"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "import-browser" -d "Import bookmarks from Chrome/Firefox/Edge/Brave profiles"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "zip-export" -d "Per-bookmark or whole-collection ZIP export"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "obsidian-export" -d "Export to Obsidian vault"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "epub-export" -d "Export bookmarks as EPUB"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "atom-export" -d "Export Atom feed"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "json-feed" -d "Export JSON Feed"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "opds-export" -d "Export OPDS 1.2 acquisition feed"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "opds2-export" -d "Export OPDS 2.0 JSON-LD acquisition feed"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "graph-export" -d "Export bookmark relationship graph JSON"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "zotero-export" -d "Export as Zotero RDF"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "encrypt" -d "Encrypt a JSON file with AES-256-GCM"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "decrypt" -d "Decrypt an encrypted JSON file"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "read-later" -d "Manage read-later queue"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "reader" -d "Manage reader highlights/notes"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "api-server" -d "Run the local HTTP API"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "mcp-server" -d "Run the MCP server (stdio)"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "mcp-http-server" -d "Run the MCP Streamable HTTP server"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "sqlite-migrate" -d "Copy JSON bookmarks into SQLite DB"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "recovery-bundle" -d "Create or restore a full-library backup"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "updates" -d "Manage update policy"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "smart-collections" -d "Manage smart collections"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "repairs" -d "Manage declarative extraction repairs"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "rules" -d "Preview and apply declarative organization rules"
complete -c bop -f -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -a "nl-query" -d "Natural language query"
complete -c bop -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -s h -d "show this help message and exit"
complete -c bop -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -l help -d "show this help message and exit"
complete -c bop -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -l version -d "show program's version number and exit"
complete -c bop -n "not __fish_seen_subcommand_from list add delete trash search import migration export categories tags stats check help ai-audit ingest transcript structured snapshot embed semantic hybrid summarize chat ask lint-tags dups scan digest flow feed jobs imports import-pocket import-firefox-backup import-readwise import-pinboard import-instapaper import-reddit import-matter import-zotero import-wallabag import-arc import-omnivore import-csv import-browser zip-export obsidian-export epub-export atom-export json-feed opds-export opds2-export graph-export zotero-export encrypt decrypt read-later reader api-server mcp-server mcp-http-server sqlite-migrate recovery-bundle updates smart-collections repairs rules nl-query" -s V -d "show program's version number and exit"
complete -c bop -n "__fish_seen_subcommand_from list" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from list" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from list" -l all -d "Show all bookmarks"
complete -c bop -n "__fish_seen_subcommand_from add" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from add" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from delete" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from delete" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from delete" -l force -d "==SUPPRESS=="
complete -c bop -n "__fish_seen_subcommand_from delete" -s y -d "==SUPPRESS=="
complete -c bop -n "__fish_seen_subcommand_from delete" -l yes -d "==SUPPRESS=="
complete -c bop -n "__fish_seen_subcommand_from trash" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from trash" -l help -d "show this help message and exit"
complete -c bop -f -n "__fish_seen_subcommand_from trash" -a "list" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from trash" -a "restore" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from trash" -a "purge" -d ""
complete -c bop -n "__fish_seen_subcommand_from search" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from search" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import" -l dry-run -d "For a directory, show the batch plan without importing"
complete -c bop -n "__fish_seen_subcommand_from migration" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from migration" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from migration" -l report -d "Optional JSON report output path" -r
complete -c bop -f -n "__fish_seen_subcommand_from migration" -a "preflight" -d "Parse only or import after preflight"
complete -c bop -f -n "__fish_seen_subcommand_from migration" -a "apply" -d "Parse only or import after preflight"
complete -c bop -f -n "__fish_seen_subcommand_from migration" -a "linkwarden" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from migration" -a "karakeep" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from migration" -a "raindrop" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from migration" -a "readwise" -d ""
complete -c bop -n "__fish_seen_subcommand_from export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from categories" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from categories" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from tags" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from tags" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from stats" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from stats" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from check" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from check" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from help" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from help" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from ai-audit" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from ai-audit" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from ai-audit" -l min-confidence -d "Ignore AI categories below this (default 0.7)" -r
complete -c bop -n "__fish_seen_subcommand_from ai-audit" -l min-support -d "Require >= N confident samples per domain (default 2)" -r
complete -c bop -n "__fish_seen_subcommand_from ai-audit" -l json -d "Print the full machine-readable JSON report"
complete -c bop -n "__fish_seen_subcommand_from ai-audit" -l out -d "Write the full JSON report to FILE" -r
complete -c bop -n "__fish_seen_subcommand_from ingest" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from ingest" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from ingest" -l templates -d "Optional JSON/YAML structured extraction templates" -r
complete -c bop -n "__fish_seen_subcommand_from transcript" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from transcript" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from transcript" -l lang -d "Subtitle language, such as en or pt-BR" -r
complete -c bop -n "__fish_seen_subcommand_from transcript" -l language -d "Subtitle language, such as en or pt-BR" -r
complete -c bop -n "__fish_seen_subcommand_from transcript" -l timeout -d "Provider timeout in seconds (1-300)" -r
complete -c bop -n "__fish_seen_subcommand_from transcript" -l remove -d "Remove the stored transcript"
complete -c bop -n "__fish_seen_subcommand_from transcript" -l json -d "Print machine-readable result"
complete -c bop -n "__fish_seen_subcommand_from structured" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from structured" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from structured" -l json -d "Print raw JSON payload"
complete -c bop -n "__fish_seen_subcommand_from snapshot" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from snapshot" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from embed" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from embed" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from embed" -l model -d "Embedding model name or key" -r
complete -c bop -n "__fish_seen_subcommand_from semantic" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from semantic" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from hybrid" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from hybrid" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from hybrid" -l limit -d "Results per page (default: 15)" -r
complete -c bop -n "__fish_seen_subcommand_from hybrid" -l offset -d "Skip this many results" -r
complete -c bop -n "__fish_seen_subcommand_from summarize" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from summarize" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from chat" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from chat" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from ask" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from ask" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from lint-tags" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from lint-tags" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from lint-tags" -l apply -d "Apply merge fixes"
complete -c bop -n "__fish_seen_subcommand_from dups" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from dups" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from dups" -l category -d "Only compare bookmarks in this collection (avoids the pairwise cap)" -r
complete -c bop -n "__fish_seen_subcommand_from dups" -l json -d "Emit the report as JSON"
complete -c bop -n "__fish_seen_subcommand_from scan" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from scan" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from scan" -l hours -d "Only scan unchecked for N hours" -r
complete -c bop -n "__fish_seen_subcommand_from digest" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from digest" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from flow" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from flow" -l help -d "show this help message and exit"
complete -c bop -f -n "__fish_seen_subcommand_from flow" -a "list" -d "Action: list, new, add, show"
complete -c bop -f -n "__fish_seen_subcommand_from flow" -a "new" -d "Action: list, new, add, show"
complete -c bop -f -n "__fish_seen_subcommand_from flow" -a "add" -d "Action: list, new, add, show"
complete -c bop -f -n "__fish_seen_subcommand_from flow" -a "show" -d "Action: list, new, add, show"
complete -c bop -n "__fish_seen_subcommand_from feed" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from feed" -l help -d "show this help message and exit"
complete -c bop -f -n "__fish_seen_subcommand_from feed" -a "list" -d "Action: list, add, remove, fetch"
complete -c bop -f -n "__fish_seen_subcommand_from feed" -a "add" -d "Action: list, add, remove, fetch"
complete -c bop -f -n "__fish_seen_subcommand_from feed" -a "remove" -d "Action: list, add, remove, fetch"
complete -c bop -f -n "__fish_seen_subcommand_from feed" -a "fetch" -d "Action: list, add, remove, fetch"
complete -c bop -n "__fish_seen_subcommand_from jobs" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from jobs" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from jobs" -l type -d "Filter by job type" -r
complete -c bop -n "__fish_seen_subcommand_from jobs" -l outcome -d "" -r -a "running" -a "success" -a "failure" -a "cancelled"
complete -c bop -n "__fish_seen_subcommand_from jobs" -l retryable -d "Show retryable jobs only"
complete -c bop -n "__fish_seen_subcommand_from jobs" -l limit -d "" -r
complete -c bop -n "__fish_seen_subcommand_from jobs" -l json -d ""
complete -c bop -f -n "__fish_seen_subcommand_from jobs" -a "health" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from jobs" -a "list" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from jobs" -a "retry" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from jobs" -a "clear" -d ""
complete -c bop -n "__fish_seen_subcommand_from imports" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from imports" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from imports" -l limit -d "" -r
complete -c bop -n "__fish_seen_subcommand_from imports" -l json -d ""
complete -c bop -f -n "__fish_seen_subcommand_from imports" -a "list" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from imports" -a "show" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from imports" -a "retry" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from imports" -a "cancel" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from imports" -a "rollback" -d ""
complete -c bop -n "__fish_seen_subcommand_from import-pocket" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-pocket" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-firefox-backup" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-firefox-backup" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-readwise" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-readwise" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-pinboard" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-pinboard" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-instapaper" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-instapaper" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-reddit" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-reddit" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-matter" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-matter" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-zotero" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-zotero" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-wallabag" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-wallabag" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-arc" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-arc" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-omnivore" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-omnivore" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-csv" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-csv" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-csv" -l map -d "Override a column mapping, e.g. --map url=Address (repeatable)" -r
complete -c bop -n "__fish_seen_subcommand_from import-csv" -l show-columns -d "Print the header row and the detected mapping, then exit"
complete -c bop -n "__fish_seen_subcommand_from import-browser" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-browser" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from import-browser" -l profile -d "Profile name (default: Default)" -r
complete -c bop -f -n "__fish_seen_subcommand_from import-browser" -a "chrome" -d "Browser to import from (auto-detect if omitted)"
complete -c bop -f -n "__fish_seen_subcommand_from import-browser" -a "firefox" -d "Browser to import from (auto-detect if omitted)"
complete -c bop -f -n "__fish_seen_subcommand_from import-browser" -a "edge" -d "Browser to import from (auto-detect if omitted)"
complete -c bop -f -n "__fish_seen_subcommand_from import-browser" -a "brave" -d "Browser to import from (auto-detect if omitted)"
complete -c bop -n "__fish_seen_subcommand_from zip-export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from zip-export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from obsidian-export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from obsidian-export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from obsidian-export" -l tag -d "Filter by tag" -r
complete -c bop -n "__fish_seen_subcommand_from obsidian-export" -l category -d "Filter by category" -r
complete -c bop -n "__fish_seen_subcommand_from obsidian-export" -l since -d "Filter by date" -r
complete -c bop -n "__fish_seen_subcommand_from epub-export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from epub-export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from epub-export" -l title -d "EPUB title" -r
complete -c bop -n "__fish_seen_subcommand_from epub-export" -l output -d "Output path" -r
complete -c bop -n "__fish_seen_subcommand_from epub-export" -l tag -d "Filter by tag" -r
complete -c bop -n "__fish_seen_subcommand_from atom-export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from atom-export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from atom-export" -l title -d "Feed title" -r
complete -c bop -n "__fish_seen_subcommand_from atom-export" -l output -d "Output path" -r
complete -c bop -n "__fish_seen_subcommand_from atom-export" -l tag -d "Filter by tag" -r
complete -c bop -n "__fish_seen_subcommand_from json-feed" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from json-feed" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from json-feed" -l title -d "Feed title" -r
complete -c bop -n "__fish_seen_subcommand_from json-feed" -l output -d "Output path" -r
complete -c bop -n "__fish_seen_subcommand_from json-feed" -l tag -d "Filter by tag" -r
complete -c bop -n "__fish_seen_subcommand_from opds-export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from opds-export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from opds-export" -l title -d "Feed title" -r
complete -c bop -n "__fish_seen_subcommand_from opds-export" -l output -d "Output path" -r
complete -c bop -n "__fish_seen_subcommand_from opds-export" -l tag -d "Filter by tag" -r
complete -c bop -n "__fish_seen_subcommand_from opds-export" -l catalog-url -d "Catalog URL" -r
complete -c bop -n "__fish_seen_subcommand_from opds2-export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from opds2-export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from opds2-export" -l title -d "Feed title" -r
complete -c bop -n "__fish_seen_subcommand_from opds2-export" -l output -d "Output path" -r
complete -c bop -n "__fish_seen_subcommand_from opds2-export" -l tag -d "Filter by tag" -r
complete -c bop -n "__fish_seen_subcommand_from opds2-export" -l catalog-url -d "Catalog URL" -r
complete -c bop -n "__fish_seen_subcommand_from graph-export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from graph-export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from graph-export" -l output -d "Output path" -r
complete -c bop -n "__fish_seen_subcommand_from graph-export" -l limit -d "Max bookmarks (default 300)" -r
complete -c bop -n "__fish_seen_subcommand_from zotero-export" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from zotero-export" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from encrypt" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from encrypt" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from encrypt" -l no-recovery -d "Skip recovery key generation"
complete -c bop -n "__fish_seen_subcommand_from decrypt" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from decrypt" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from decrypt" -l recovery-key -d "Decrypt using recovery key instead of passphrase" -r
complete -c bop -n "__fish_seen_subcommand_from read-later" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from read-later" -l help -d "show this help message and exit"
complete -c bop -f -n "__fish_seen_subcommand_from read-later" -a "add" -d "Action: add, next, done, list"
complete -c bop -f -n "__fish_seen_subcommand_from read-later" -a "next" -d "Action: add, next, done, list"
complete -c bop -f -n "__fish_seen_subcommand_from read-later" -a "done" -d "Action: add, next, done, list"
complete -c bop -f -n "__fish_seen_subcommand_from read-later" -a "list" -d "Action: add, next, done, list"
complete -c bop -n "__fish_seen_subcommand_from reader" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from reader" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from reader" -l color -d "Filter color, or highlight color for add (default: yellow for add)" -r -a "yellow" -a "green" -a "blue" -a "pink"
complete -c bop -n "__fish_seen_subcommand_from reader" -l note -d "Note text" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l text -d "Filter selected highlight text" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l note-filter -d "Filter highlight notes" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l tag -d "Filter highlight tags" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l bookmark-id -d "Filter the global workspace by bookmark ID" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l review -d "Filter review state" -r -a "all" -a "new" -a "due" -a "scheduled" -a "reviewed"
complete -c bop -n "__fish_seen_subcommand_from reader" -l anchor -d "Filter anchor state" -r -a "all" -a "anchored" -a "reanchored" -a "orphaned" -a "unverified"
complete -c bop -n "__fish_seen_subcommand_from reader" -l limit -d "Global workspace page size" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l offset -d "Global workspace page offset" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l output -d "Export output directory" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l format -d "Reader export format (default: markdown)" -r -a "markdown" -a "csv" -a "json"
complete -c bop -n "__fish_seen_subcommand_from reader" -l template -d "JSON annotation export template" -r
complete -c bop -n "__fish_seen_subcommand_from reader" -l changed-since -d "Only export highlights modified at/after ISO timestamp" -r
complete -c bop -f -n "__fish_seen_subcommand_from reader" -a "list" -d "Action: list, add, note, delete, due, review, export"
complete -c bop -f -n "__fish_seen_subcommand_from reader" -a "add" -d "Action: list, add, note, delete, due, review, export"
complete -c bop -f -n "__fish_seen_subcommand_from reader" -a "note" -d "Action: list, add, note, delete, due, review, export"
complete -c bop -f -n "__fish_seen_subcommand_from reader" -a "delete" -d "Action: list, add, note, delete, due, review, export"
complete -c bop -f -n "__fish_seen_subcommand_from reader" -a "due" -d "Action: list, add, note, delete, due, review, export"
complete -c bop -f -n "__fish_seen_subcommand_from reader" -a "review" -d "Action: list, add, note, delete, due, review, export"
complete -c bop -f -n "__fish_seen_subcommand_from reader" -a "export" -d "Action: list, add, note, delete, due, review, export"
complete -c bop -n "__fish_seen_subcommand_from api-server" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from api-server" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from api-server" -l port -d "Port number (default 8765)" -r
complete -c bop -n "__fish_seen_subcommand_from mcp-server" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from mcp-server" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from mcp-http-server" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from mcp-http-server" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from mcp-http-server" -l host -d "Host (default 127.0.0.1)" -r
complete -c bop -n "__fish_seen_subcommand_from mcp-http-server" -l port -d "Port (default 8766)" -r
complete -c bop -n "__fish_seen_subcommand_from mcp-http-server" -l path -d "Endpoint path (default /mcp)" -r
complete -c bop -n "__fish_seen_subcommand_from sqlite-migrate" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from sqlite-migrate" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from sqlite-migrate" -l source -d "Source JSON file" -r
complete -c bop -n "__fish_seen_subcommand_from sqlite-migrate" -l dest -d "Destination SQLite DB" -r
complete -c bop -n "__fish_seen_subcommand_from recovery-bundle" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from recovery-bundle" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from recovery-bundle" -l apply -d "Apply a verified restore (restore is validation-only by default)"
complete -c bop -f -n "__fish_seen_subcommand_from recovery-bundle" -a "create" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from recovery-bundle" -a "validate" -d ""
complete -c bop -f -n "__fish_seen_subcommand_from recovery-bundle" -a "restore" -d ""
complete -c bop -n "__fish_seen_subcommand_from updates" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from updates" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from updates" -l dry-run -d "Preflight check only"
complete -c bop -n "__fish_seen_subcommand_from updates" -l preflight -d "Preflight check only"
complete -c bop -n "__fish_seen_subcommand_from updates" -l enable -d "Enable updates"
complete -c bop -n "__fish_seen_subcommand_from updates" -l disable -d "Disable updates"
complete -c bop -n "__fish_seen_subcommand_from updates" -l metadata-url -d "Metadata URL" -r
complete -c bop -n "__fish_seen_subcommand_from updates" -l targets-url -d "Targets URL" -r
complete -c bop -n "__fish_seen_subcommand_from updates" -l channel -d "Update channel" -r
complete -c bop -n "__fish_seen_subcommand_from updates" -l allow-prerelease -d "Allow prerelease"
complete -c bop -n "__fish_seen_subcommand_from updates" -l no-prerelease -d "Disallow prerelease"
complete -c bop -f -n "__fish_seen_subcommand_from updates" -a "status" -d "Action (default: status)"
complete -c bop -f -n "__fish_seen_subcommand_from updates" -a "check" -d "Action (default: status)"
complete -c bop -f -n "__fish_seen_subcommand_from updates" -a "configure" -d "Action (default: status)"
complete -c bop -f -n "__fish_seen_subcommand_from updates" -a "download" -d "Action (default: status)"
complete -c bop -f -n "__fish_seen_subcommand_from updates" -a "staged" -d "Action (default: status)"
complete -c bop -f -n "__fish_seen_subcommand_from updates" -a "clean-staged" -d "Action (default: status)"
complete -c bop -f -n "__fish_seen_subcommand_from updates" -a "plan" -d "Action (default: status)"
complete -c bop -f -n "__fish_seen_subcommand_from updates" -a "apply" -d "Action (default: status)"
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l name -d "Replacement name for update" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l icon -d "Collection icon" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l tags -d "Comma-separated tags" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l categories -d "Comma-separated categories" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l domains -d "Comma-separated exact domains" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l content-types -d "Comma-separated content types" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l keywords -d "Comma-separated keywords" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l after -d "ISO-8601 lower date bound" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l before -d "ISO-8601 upper date bound" -r
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l read-later-only -d ""
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l no-read-later-only -d ""
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l has-snapshot -d ""
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l no-has-snapshot -d ""
complete -c bop -n "__fish_seen_subcommand_from smart-collections" -l reader-state -d "Filter by persisted reader state" -r -a "unread" -a "in_progress" -a "finished"
complete -c bop -f -n "__fish_seen_subcommand_from smart-collections" -a "list" -d "Action: list, eval, create, update"
complete -c bop -f -n "__fish_seen_subcommand_from smart-collections" -a "eval" -d "Action: list, eval, create, update"
complete -c bop -f -n "__fish_seen_subcommand_from smart-collections" -a "create" -d "Action: list, eval, create, update"
complete -c bop -f -n "__fish_seen_subcommand_from smart-collections" -a "update" -d "Action: list, eval, create, update"
complete -c bop -n "__fish_seen_subcommand_from repairs" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from repairs" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from repairs" -l url -d "Page URL to preview a repair against" -r
complete -c bop -n "__fish_seen_subcommand_from repairs" -l html -d "Local HTML file to preview a repair against" -r
complete -c bop -n "__fish_seen_subcommand_from repairs" -l domain -d "Domain the repair applies to (repeatable)" -r
complete -c bop -n "__fish_seen_subcommand_from repairs" -l keep -d "Selector for the element holding the article body" -r
complete -c bop -n "__fish_seen_subcommand_from repairs" -l drop -d "Selector for boilerplate to remove (repeatable)" -r
complete -c bop -n "__fish_seen_subcommand_from repairs" -l name -d "Name of the repair to add or remove" -r
complete -c bop -n "__fish_seen_subcommand_from repairs" -l max-length -d "Cap on repaired text length" -r
complete -c bop -n "__fish_seen_subcommand_from repairs" -l json -d "Machine-readable output"
complete -c bop -f -n "__fish_seen_subcommand_from repairs" -a "list" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from repairs" -a "preview" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from repairs" -a "add" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from repairs" -a "remove" -d "Action (default: list)"
complete -c bop -n "__fish_seen_subcommand_from rules" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from rules" -l help -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from rules" -l replace -d "Replace existing rules during import"
complete -c bop -n "__fish_seen_subcommand_from rules" -l min-support -d "Bookmarks that must agree before a rule is suggested (default: 3)" -r
complete -c bop -n "__fish_seen_subcommand_from rules" -l adopt -d "Save every suggested rule instead of only listing them"
complete -c bop -n "__fish_seen_subcommand_from rules" -l json -d "Print machine-readable output"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "list" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "preview" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "apply" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "undo" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "import" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "export" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "enable" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "disable" -d "Action (default: list)"
complete -c bop -f -n "__fish_seen_subcommand_from rules" -a "suggest" -d "Action (default: list)"
complete -c bop -n "__fish_seen_subcommand_from nl-query" -s h -d "show this help message and exit"
complete -c bop -n "__fish_seen_subcommand_from nl-query" -l help -d "show this help message and exit"
