# Generated by scripts/generate_completions.py; do not edit.
# bash completion for bop (Bookmark Organizer Pro)
# Source this file: . bop.bash OR copy to /etc/bash_completion.d/

_bop_complete_array() {
    local cur="$1"
    shift
    COMPREPLY=()
    local candidate
    for candidate in "$@"; do
        if [[ "$candidate" == "$cur"* ]]; then
            COMPREPLY+=("$candidate")
        fi
    done
}

_bop_complete_files() {
    mapfile -t COMPREPLY < <(compgen -f -- "$1")
}

_bop_completions() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev=""
    if (( COMP_CWORD > 0 )); then prev="${COMP_WORDS[COMP_CWORD-1]}"; fi
    local cmd=""
    if (( COMP_CWORD > 1 )); then cmd="${COMP_WORDS[1]}"; fi
    local -a commands=(
        list
        add
        delete
        search
        import
        migration
        export
        categories
        tags
        stats
        check
        help
        ai-audit
        ingest
        transcript
        structured
        snapshot
        embed
        semantic
        hybrid
        summarize
        chat
        ask
        lint-tags
        dups
        scan
        digest
        flow
        feed
        jobs
        imports
        import-pocket
        import-firefox-backup
        import-readwise
        import-pinboard
        import-instapaper
        import-reddit
        import-matter
        import-zotero
        import-wallabag
        import-arc
        import-omnivore
        import-csv
        import-browser
        zip-export
        obsidian-export
        epub-export
        atom-export
        json-feed
        opds-export
        opds2-export
        graph-export
        zotero-export
        encrypt
        decrypt
        read-later
        reader
        api-server
        mcp-server
        mcp-http-server
        sqlite-migrate
        recovery-bundle
        updates
        smart-collections
        repairs
        rules
        nl-query
    )
    local -a global_options=(
        -h
        --help
        --version
        -V
    )
    if (( COMP_CWORD <= 1 )); then
        _bop_complete_array "$cur" "${commands[@]}" "${global_options[@]}"
        return 0
    fi

    case "$cmd" in
        list)
            local -a options=(
                -h
                --help
                --all
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        add)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        delete)
            local -a options=(
                -h
                --help
                --force
                -y
                --yes
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        search)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        import)
            local -a options=(
                -h
                --help
                --dry-run
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        migration)
            local -a options=(
                -h
                --help
                --report
            )
            case "$prev" in
                --report)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    preflight
                    apply
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            if (( COMP_CWORD == 3 )); then
                local -a values=(
                    linkwarden
                    karakeep
                    raindrop
                    readwise
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            if (( COMP_CWORD == 4 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        export)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        categories)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        tags)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        stats)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        check)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        help)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        ai-audit)
            local -a options=(
                -h
                --help
                --min-confidence
                --min-support
                --json
                --out
            )
            case "$prev" in
                --min-confidence)
                    return 0
                    ;;
                --min-support)
                    return 0
                    ;;
                --out)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        ingest)
            local -a options=(
                -h
                --help
                --templates
            )
            case "$prev" in
                --templates)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        transcript)
            local -a options=(
                -h
                --help
                --lang
                --language
                --timeout
                --remove
                --json
            )
            case "$prev" in
                --lang)
                    return 0
                    ;;
                --language)
                    return 0
                    ;;
                --timeout)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        structured)
            local -a options=(
                -h
                --help
                --json
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        snapshot)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        embed)
            local -a options=(
                -h
                --help
                --model
            )
            case "$prev" in
                --model)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        semantic)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        hybrid)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        summarize)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        chat)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        ask)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        lint-tags)
            local -a options=(
                -h
                --help
                --apply
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        dups)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        scan)
            local -a options=(
                -h
                --help
                --hours
            )
            case "$prev" in
                --hours)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        digest)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        flow)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    list
                    new
                    add
                    show
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        feed)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    list
                    add
                    remove
                    fetch
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        jobs)
            local -a options=(
                -h
                --help
                --type
                --outcome
                --retryable
                --limit
                --json
            )
            case "$prev" in
                --type)
                    return 0
                    ;;
                --outcome)
                    local -a values=(
                        running
                        success
                        failure
                        cancelled
                    )
                    _bop_complete_array "$cur" "${values[@]}"
                    return 0
                    return 0
                    ;;
                --limit)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    health
                    list
                    retry
                    clear
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        imports)
            local -a options=(
                -h
                --help
                --limit
                --json
            )
            case "$prev" in
                --limit)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    list
                    show
                    retry
                    cancel
                    rollback
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        import-pocket)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-firefox-backup)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-readwise)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-pinboard)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-instapaper)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-reddit)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-matter)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-zotero)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-wallabag)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-arc)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-omnivore)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-csv)
            local -a options=(
                -h
                --help
                --map
                --show-columns
            )
            case "$prev" in
                --map)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        import-browser)
            local -a options=(
                -h
                --help
                --profile
            )
            case "$prev" in
                --profile)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    chrome
                    firefox
                    edge
                    brave
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        zip-export)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 3 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        obsidian-export)
            local -a options=(
                -h
                --help
                --tag
                --category
                --since
            )
            case "$prev" in
                --tag)
                    return 0
                    ;;
                --category)
                    return 0
                    ;;
                --since)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        epub-export)
            local -a options=(
                -h
                --help
                --title
                --output
                --tag
            )
            case "$prev" in
                --title)
                    return 0
                    ;;
                --output)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --tag)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        atom-export)
            local -a options=(
                -h
                --help
                --title
                --output
                --tag
            )
            case "$prev" in
                --title)
                    return 0
                    ;;
                --output)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --tag)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        json-feed)
            local -a options=(
                -h
                --help
                --title
                --output
                --tag
            )
            case "$prev" in
                --title)
                    return 0
                    ;;
                --output)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --tag)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        opds-export)
            local -a options=(
                -h
                --help
                --title
                --output
                --tag
                --catalog-url
            )
            case "$prev" in
                --title)
                    return 0
                    ;;
                --output)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --tag)
                    return 0
                    ;;
                --catalog-url)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        opds2-export)
            local -a options=(
                -h
                --help
                --title
                --output
                --tag
                --catalog-url
            )
            case "$prev" in
                --title)
                    return 0
                    ;;
                --output)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --tag)
                    return 0
                    ;;
                --catalog-url)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        graph-export)
            local -a options=(
                -h
                --help
                --output
                --limit
            )
            case "$prev" in
                --output)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --limit)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        zotero-export)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        encrypt)
            local -a options=(
                -h
                --help
                --no-recovery
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 3 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            if (( COMP_CWORD == 4 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        decrypt)
            local -a options=(
                -h
                --help
                --recovery-key
            )
            case "$prev" in
                --recovery-key)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 3 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            if (( COMP_CWORD == 4 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        read-later)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    add
                    next
                    done
                    list
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        reader)
            local -a options=(
                -h
                --help
                --color
                --note
                --text
                --note-filter
                --tag
                --bookmark-id
                --review
                --anchor
                --limit
                --offset
                --output
                --format
                --template
                --changed-since
            )
            case "$prev" in
                --color)
                    local -a values=(
                        yellow
                        green
                        blue
                        pink
                    )
                    _bop_complete_array "$cur" "${values[@]}"
                    return 0
                    return 0
                    ;;
                --note)
                    return 0
                    ;;
                --text)
                    return 0
                    ;;
                --note-filter)
                    return 0
                    ;;
                --tag)
                    return 0
                    ;;
                --bookmark-id)
                    return 0
                    ;;
                --review)
                    local -a values=(
                        all
                        new
                        due
                        scheduled
                        reviewed
                    )
                    _bop_complete_array "$cur" "${values[@]}"
                    return 0
                    return 0
                    ;;
                --anchor)
                    local -a values=(
                        all
                        anchored
                        reanchored
                        orphaned
                        unverified
                    )
                    _bop_complete_array "$cur" "${values[@]}"
                    return 0
                    return 0
                    ;;
                --limit)
                    return 0
                    ;;
                --offset)
                    return 0
                    ;;
                --output)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --format)
                    local -a values=(
                        markdown
                        csv
                        json
                    )
                    _bop_complete_array "$cur" "${values[@]}"
                    return 0
                    return 0
                    ;;
                --template)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --changed-since)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    list
                    add
                    note
                    delete
                    due
                    review
                    export
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        api-server)
            local -a options=(
                -h
                --help
                --port
            )
            case "$prev" in
                --port)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        mcp-server)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        mcp-http-server)
            local -a options=(
                -h
                --help
                --host
                --port
                --path
            )
            case "$prev" in
                --host)
                    return 0
                    ;;
                --port)
                    return 0
                    ;;
                --path)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        sqlite-migrate)
            local -a options=(
                -h
                --help
                --source
                --dest
            )
            case "$prev" in
                --source)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --dest)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
        recovery-bundle)
            local -a options=(
                -h
                --help
                --apply
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    create
                    validate
                    restore
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            if (( COMP_CWORD == 3 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        updates)
            local -a options=(
                -h
                --help
                --dry-run
                --preflight
                --enable
                --disable
                --metadata-url
                --targets-url
                --channel
                --allow-prerelease
                --no-prerelease
            )
            case "$prev" in
                --metadata-url)
                    return 0
                    ;;
                --targets-url)
                    return 0
                    ;;
                --channel)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    status
                    check
                    configure
                    download
                    staged
                    clean-staged
                    plan
                    apply
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        smart-collections)
            local -a options=(
                -h
                --help
                --name
                --icon
                --tags
                --categories
                --domains
                --content-types
                --keywords
                --after
                --before
                --read-later-only
                --no-read-later-only
                --has-snapshot
                --no-has-snapshot
                --reader-state
            )
            case "$prev" in
                --name)
                    return 0
                    ;;
                --icon)
                    return 0
                    ;;
                --tags)
                    return 0
                    ;;
                --categories)
                    return 0
                    ;;
                --domains)
                    return 0
                    ;;
                --content-types)
                    return 0
                    ;;
                --keywords)
                    return 0
                    ;;
                --after)
                    return 0
                    ;;
                --before)
                    return 0
                    ;;
                --reader-state)
                    local -a values=(
                        unread
                        in_progress
                        finished
                    )
                    _bop_complete_array "$cur" "${values[@]}"
                    return 0
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    list
                    eval
                    create
                    update
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        repairs)
            local -a options=(
                -h
                --help
                --url
                --html
                --domain
                --keep
                --drop
                --name
                --max-length
                --json
            )
            case "$prev" in
                --url)
                    return 0
                    ;;
                --html)
                    _bop_complete_files "$cur"
                    return 0
                    return 0
                    ;;
                --domain)
                    return 0
                    ;;
                --keep)
                    return 0
                    ;;
                --drop)
                    return 0
                    ;;
                --name)
                    return 0
                    ;;
                --max-length)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    list
                    preview
                    add
                    remove
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            return 0
            ;;
        rules)
            local -a options=(
                -h
                --help
                --replace
                --min-support
                --adopt
                --json
            )
            case "$prev" in
                --min-support)
                    return 0
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            if (( COMP_CWORD == 2 )); then
                local -a values=(
                    list
                    preview
                    apply
                    undo
                    import
                    export
                    enable
                    disable
                    suggest
                )
                _bop_complete_array "$cur" "${values[@]}"
                return 0
            fi
            if (( COMP_CWORD == 3 )); then
                _bop_complete_files "$cur"
                return 0
            fi
            return 0
            ;;
        nl-query)
            local -a options=(
                -h
                --help
            )
            case "$prev" in
            esac
            if [[ "$cur" == -* ]]; then
                _bop_complete_array "$cur" "${options[@]}"
                return 0
            fi
            return 0
            ;;
    esac
    return 0
}

complete -F _bop_completions bop
