"""Theme registry and runtime providers for the desktop UI."""

from __future__ import annotations

from typing import Dict, Optional

from bookmark_organizer_pro.constants import SETTINGS_FILE, THEMES_DIR
from bookmark_organizer_pro.ui.style_manager import style_manager
from bookmark_organizer_pro.ui.theme import ThemeColors, ThemeInfo, ThemeManager
from bookmark_organizer_pro.ui.widgets import set_widget_theme_provider


# =============================================================================
# Built-in Themes
# =============================================================================
BUILT_IN_THEMES: Dict[str, ThemeInfo] = {
    "github_dark": ThemeInfo(
        name="github_dark",
        display_name="Studio",
        description="Bright editorial workspace with ink typography and mint actions",
        is_dark=False,
        colors=ThemeColors()
    ),
    
    "github_light": ThemeInfo(
        name="github_light",
        display_name="GitHub Light",
        description="Clean light theme inspired by GitHub",
        is_dark=False,
        colors=ThemeColors(
            bg_dark="#ffffff",
            bg_primary="#f6f8fa",
            bg_secondary="#ffffff",
            bg_tertiary="#f0f0f0",
            bg_hover="#e8e8e8",
            bg_card="#ffffff",
            text_primary="#24292f",
            text_secondary="#57606a",
            text_muted="#8c959f",
            text_link="#0969da",
            accent_primary="#0969da",
            accent_success="#1a7f37",
            accent_warning="#9a6700",
            accent_error="#cf222e",
            accent_purple="#8250df",
            accent_cyan="#0891b2",
            accent_pink="#bf3989",
            accent_orange="#bc4c00",
            border="#d0d7de",
            border_muted="#d8dee4",
            border_active="#0969da",
            selection="#ddf4ff",
            selected="#0969da",
            hover="#f3f4f6",
            drag_target="#1a7f37",
            drag_target_bg="#dafbe1",
            drop_zone="#ddf4ff",
            drop_zone_active="#b6e3ff",
            drop_zone_border="#0969da",
            scrollbar_bg="#f0f0f0",
            scrollbar_thumb="#c1c4c8",
            scrollbar_thumb_hover="#8c959f",
            card_bg="#ffffff",
            card_border="#d0d7de",
            card_hover="#f6f8fa",
            tag_bg="#ddf4ff",
            tag_text="#0969da",
        )
    ),
    
    "dracula": ThemeInfo(
        name="dracula",
        display_name="Dracula",
        description="Popular dark theme with purple accents",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#21222c",
            bg_primary="#282a36",
            bg_secondary="#343746",
            bg_tertiary="#44475a",
            bg_hover="#44475a",
            bg_card="#282a36",
            text_primary="#f8f8f2",
            text_secondary="#bfbfbf",
            text_muted="#6272a4",
            text_link="#8be9fd",
            accent_primary="#bd93f9",
            accent_success="#50fa7b",
            accent_warning="#ffb86c",
            accent_error="#ff5555",
            accent_purple="#bd93f9",
            accent_cyan="#8be9fd",
            accent_pink="#ff79c6",
            accent_orange="#ffb86c",
            border="#44475a",
            border_muted="#343746",
            border_active="#bd93f9",
            selection="#44475a",
            selected="#6272a4",
            hover="#44475a",
            drag_target="#50fa7b",
            drag_target_bg="#2d4a35",
            scrollbar_bg="#343746",
            scrollbar_thumb="#6272a4",
            scrollbar_thumb_hover="#bd93f9",
            card_bg="#282a36",
            card_border="#44475a",
            card_hover="#343746",
            ai_accent="#bd93f9",
            tag_bg="#bd93f926",
            tag_text="#bd93f9",
        )
    ),
    
    "nord": ThemeInfo(
        name="nord",
        display_name="Nord",
        description="Arctic, north-bluish color palette",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#2e3440",
            bg_primary="#3b4252",
            bg_secondary="#434c5e",
            bg_tertiary="#4c566a",
            bg_hover="#4c566a",
            bg_card="#3b4252",
            text_primary="#eceff4",
            text_secondary="#d8dee9",
            text_muted="#7b88a1",
            text_link="#88c0d0",
            accent_primary="#81a1c1",
            accent_success="#a3be8c",
            accent_warning="#ebcb8b",
            accent_error="#bf616a",
            accent_purple="#b48ead",
            accent_cyan="#88c0d0",
            accent_pink="#b48ead",
            accent_orange="#d08770",
            border="#4c566a",
            border_muted="#434c5e",
            border_active="#81a1c1",
            selection="#4c566a",
            selected="#5e81ac",
            hover="#4c566a",
            drag_target="#a3be8c",
            drag_target_bg="#3d4a3a",
            scrollbar_bg="#434c5e",
            scrollbar_thumb="#4c566a",
            scrollbar_thumb_hover="#5e81ac",
            card_bg="#3b4252",
            card_border="#4c566a",
            card_hover="#434c5e",
            ai_accent="#b48ead",
            tag_bg="#81a1c126",
            tag_text="#81a1c1",
        )
    ),
    
    "monokai": ThemeInfo(
        name="monokai",
        display_name="Monokai Pro",
        description="Iconic color scheme with warm tones",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#1e1f1c",
            bg_primary="#272822",
            bg_secondary="#3e3d32",
            bg_tertiary="#49483e",
            bg_hover="#49483e",
            bg_card="#272822",
            text_primary="#f8f8f2",
            text_secondary="#cfcfc2",
            text_muted="#75715e",
            text_link="#66d9ef",
            accent_primary="#a6e22e",
            accent_success="#a6e22e",
            accent_warning="#e6db74",
            accent_error="#f92672",
            accent_purple="#ae81ff",
            accent_cyan="#66d9ef",
            accent_pink="#f92672",
            accent_orange="#fd971f",
            border="#49483e",
            border_muted="#3e3d32",
            border_active="#a6e22e",
            selection="#49483e",
            selected="#75715e",
            hover="#49483e",
            drag_target="#a6e22e",
            drag_target_bg="#3d4a32",
            scrollbar_bg="#3e3d32",
            scrollbar_thumb="#75715e",
            scrollbar_thumb_hover="#a6e22e",
            card_bg="#272822",
            card_border="#49483e",
            card_hover="#3e3d32",
            ai_accent="#ae81ff",
            tag_bg="#a6e22e26",
            tag_text="#a6e22e",
        )
    ),
    
    "one_dark": ThemeInfo(
        name="one_dark",
        display_name="One Dark Pro",
        description="Atom's iconic One Dark theme",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#1e2127",
            bg_primary="#282c34",
            bg_secondary="#2c313a",
            bg_tertiary="#3e4451",
            bg_hover="#3e4451",
            bg_card="#282c34",
            text_primary="#abb2bf",
            text_secondary="#9da5b3",
            text_muted="#5c6370",
            text_link="#61afef",
            accent_primary="#61afef",
            accent_success="#98c379",
            accent_warning="#e5c07b",
            accent_error="#e06c75",
            accent_purple="#c678dd",
            accent_cyan="#56b6c2",
            accent_pink="#c678dd",
            accent_orange="#d19a66",
            border="#3e4451",
            border_muted="#2c313a",
            border_active="#61afef",
            selection="#3e4451",
            selected="#4d78a9",
            hover="#3e4451",
            drag_target="#98c379",
            drag_target_bg="#2d4a35",
            scrollbar_bg="#2c313a",
            scrollbar_thumb="#5c6370",
            scrollbar_thumb_hover="#61afef",
            card_bg="#282c34",
            card_border="#3e4451",
            card_hover="#2c313a",
            ai_accent="#c678dd",
            tag_bg="#61afef26",
            tag_text="#61afef",
        )
    ),
    
    "tokyo_night": ThemeInfo(
        name="tokyo_night",
        display_name="Tokyo Night",
        description="Clean dark theme inspired by Tokyo at night",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#16161e",
            bg_primary="#1a1b26",
            bg_secondary="#24283b",
            bg_tertiary="#292e42",
            bg_hover="#292e42",
            bg_card="#1a1b26",
            text_primary="#c0caf5",
            text_secondary="#a9b1d6",
            text_muted="#565f89",
            text_link="#7aa2f7",
            accent_primary="#7aa2f7",
            accent_success="#9ece6a",
            accent_warning="#e0af68",
            accent_error="#f7768e",
            accent_purple="#bb9af7",
            accent_cyan="#7dcfff",
            accent_pink="#ff007c",
            accent_orange="#ff9e64",
            border="#292e42",
            border_muted="#24283b",
            border_active="#7aa2f7",
            selection="#283457",
            selected="#3d59a1",
            hover="#292e42",
            drag_target="#9ece6a",
            drag_target_bg="#2a3a2a",
            scrollbar_bg="#24283b",
            scrollbar_thumb="#565f89",
            scrollbar_thumb_hover="#7aa2f7",
            card_bg="#1a1b26",
            card_border="#292e42",
            card_hover="#24283b",
            ai_accent="#bb9af7",
            tag_bg="#7aa2f726",
            tag_text="#7aa2f7",
        )
    ),
    
    "gruvbox_dark": ThemeInfo(
        name="gruvbox_dark",
        display_name="Gruvbox Dark",
        description="Retro groove color scheme",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#1d2021",
            bg_primary="#282828",
            bg_secondary="#3c3836",
            bg_tertiary="#504945",
            bg_hover="#504945",
            bg_card="#282828",
            text_primary="#ebdbb2",
            text_secondary="#d5c4a1",
            text_muted="#928374",
            text_link="#83a598",
            accent_primary="#fabd2f",
            accent_success="#b8bb26",
            accent_warning="#fabd2f",
            accent_error="#fb4934",
            accent_purple="#d3869b",
            accent_cyan="#8ec07c",
            accent_pink="#d3869b",
            accent_orange="#fe8019",
            border="#504945",
            border_muted="#3c3836",
            border_active="#fabd2f",
            selection="#504945",
            selected="#665c54",
            hover="#504945",
            drag_target="#b8bb26",
            drag_target_bg="#3a4a2a",
            scrollbar_bg="#3c3836",
            scrollbar_thumb="#665c54",
            scrollbar_thumb_hover="#fabd2f",
            card_bg="#282828",
            card_border="#504945",
            card_hover="#3c3836",
            ai_accent="#d3869b",
            tag_bg="#fabd2f26",
            tag_text="#fabd2f",
        )
    ),
    
    "solarized_dark": ThemeInfo(
        name="solarized_dark",
        display_name="Solarized Dark",
        description="Precision colors for machines and people",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#002b36",
            bg_primary="#073642",
            bg_secondary="#0a4452",
            bg_tertiary="#1c5766",
            bg_hover="#1c5766",
            bg_card="#073642",
            text_primary="#839496",
            text_secondary="#93a1a1",
            text_muted="#586e75",
            text_link="#268bd2",
            accent_primary="#268bd2",
            accent_success="#859900",
            accent_warning="#b58900",
            accent_error="#dc322f",
            accent_purple="#6c71c4",
            accent_cyan="#2aa198",
            accent_pink="#d33682",
            accent_orange="#cb4b16",
            border="#1c5766",
            border_muted="#0a4452",
            border_active="#268bd2",
            selection="#1c5766",
            selected="#2aa198",
            hover="#1c5766",
            drag_target="#859900",
            drag_target_bg="#2a3a1a",
            scrollbar_bg="#0a4452",
            scrollbar_thumb="#586e75",
            scrollbar_thumb_hover="#268bd2",
            card_bg="#073642",
            card_border="#1c5766",
            card_hover="#0a4452",
            ai_accent="#6c71c4",
            tag_bg="#268bd226",
            tag_text="#268bd2",
        )
    ),
    
    "catppuccin_mocha": ThemeInfo(
        name="catppuccin_mocha",
        display_name="Catppuccin Mocha",
        description="Soothing pastel theme for the high-spirited",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#11111b",
            bg_primary="#1e1e2e",
            bg_secondary="#313244",
            bg_tertiary="#45475a",
            bg_hover="#45475a",
            bg_card="#1e1e2e",
            text_primary="#cdd6f4",
            text_secondary="#bac2de",
            text_muted="#6c7086",
            text_link="#89b4fa",
            accent_primary="#89b4fa",
            accent_success="#a6e3a1",
            accent_warning="#f9e2af",
            accent_error="#f38ba8",
            accent_purple="#cba6f7",
            accent_cyan="#94e2d5",
            accent_pink="#f5c2e7",
            accent_orange="#fab387",
            border="#45475a",
            border_muted="#313244",
            border_active="#89b4fa",
            selection="#45475a",
            selected="#585b70",
            hover="#45475a",
            drag_target="#a6e3a1",
            drag_target_bg="#2a4a35",
            scrollbar_bg="#313244",
            scrollbar_thumb="#6c7086",
            scrollbar_thumb_hover="#89b4fa",
            card_bg="#1e1e2e",
            card_border="#45475a",
            card_hover="#313244",
            ai_accent="#cba6f7",
            tag_bg="#89b4fa26",
            tag_text="#89b4fa",
        )
    ),
    
    "midnight_blue": ThemeInfo(
        name="midnight_blue",
        display_name="Midnight Blue",
        description="Deep blue professional theme",
        is_dark=True,
        colors=ThemeColors(
            bg_dark="#0a0e14",
            bg_primary="#0d1117",
            bg_secondary="#151b23",
            bg_tertiary="#1e2630",
            bg_hover="#263040",
            bg_card="#0d1117",
            text_primary="#e6edf3",
            text_secondary="#b0b8c1",
            text_muted="#6b7280",
            text_link="#60a5fa",
            accent_primary="#3b82f6",
            accent_success="#22c55e",
            accent_warning="#f59e0b",
            accent_error="#ef4444",
            accent_purple="#a855f7",
            accent_cyan="#06b6d4",
            accent_pink="#ec4899",
            accent_orange="#f97316",
            border="#1e2630",
            border_muted="#151b23",
            border_active="#3b82f6",
            selection="#1e3a5f",
            selected="#2563eb",
            hover="#1e2630",
            drag_target="#22c55e",
            drag_target_bg="#1a3a2a",
            scrollbar_bg="#151b23",
            scrollbar_thumb="#374151",
            scrollbar_thumb_hover="#3b82f6",
            card_bg="#0d1117",
            card_border="#1e2630",
            card_hover="#151b23",
            ai_accent="#a855f7",
            tag_bg="#3b82f626",
            tag_text="#60a5fa",
        )
    ),
}

# Global theme manager instance
_theme_manager: Optional[ThemeManager] = None
_theme_style_callback_registered = False


def _apply_theme_to_ttk(theme_info: ThemeInfo):
    """Bridge toolkit-neutral theme changes into ttk style repainting."""
    if style_manager._initialized:
        style_manager.apply_theme(theme_info.colors)

def get_theme_manager() -> ThemeManager:
    """Get the global theme manager instance"""
    global _theme_manager, _theme_style_callback_registered
    if _theme_manager is None:
        _theme_manager = ThemeManager(
            BUILT_IN_THEMES,
            settings_file=SETTINGS_FILE,
            themes_dir=THEMES_DIR,
            default_theme="github_dark",
        )
    if not _theme_style_callback_registered:
        _theme_manager.add_theme_change_callback(_apply_theme_to_ttk)
        _theme_style_callback_registered = True
    return _theme_manager

def get_theme() -> ThemeColors:
    """Get current theme colors (convenience function)"""
    return get_theme_manager().colors


set_widget_theme_provider(get_theme)

