"""User-facing analytics report generation."""

from __future__ import annotations

import html
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Iterable, List, Mapping, Tuple

from .theme import ThemeColors


class ReportGenerator:
    """Generate bookmark analytics reports in HTML and plain text."""

    def __init__(
        self,
        bookmark_manager: Any,
        theme_provider: Callable[[], ThemeColors] = ThemeColors,
        app_name: str = "Bookmark Organizer Pro",
        app_version: str = "",
    ):
        self.bookmark_manager = bookmark_manager
        self.theme_provider = theme_provider
        self.app_name = app_name
        self.app_version = app_version

    def generate_html_report(self, filepath: str) -> None:
        """Generate an HTML analytics report with escaped user data."""
        stats = self.bookmark_manager.get_statistics()
        theme = self.theme_provider()
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

        category_rows = "\n".join(
            self._category_row(name, count, _int_stat(stats, "total_bookmarks") or 1)
            for name, count in _sorted_counts(stats.get("category_counts", {}))
        )
        domain_rows = "\n".join(
            f"<tr><td>{html.escape(str(domain))}</td><td>{int(count or 0)}</td></tr>"
            for domain, count in _sequence_counts(stats.get("top_domains", []))[:15]
        )
        age_rows = "\n".join(
            f"<tr><td>{html.escape(str(period))}</td><td>{int(count or 0)}</td></tr>"
            for period, count in _sequence_counts(stats.get("age_distribution", {}).items())
        )

        document = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookmark Analytics Report</title>
    <style>
        :root {{ color-scheme: dark; }}
        body {{
            font-family: "Segoe UI", Arial, sans-serif;
            background: {theme.bg_primary};
            color: {theme.text_primary};
            margin: 0;
            padding: 40px;
        }}
        .container {{ max-width: 1040px; margin: 0 auto; }}
        .eyebrow {{ color: {theme.text_muted}; font-size: 12px; letter-spacing: .08em; text-transform: uppercase; }}
        h1 {{ color: {theme.text_primary}; margin: 8px 0 6px; }}
        h2 {{ color: {theme.text_secondary}; margin-top: 34px; }}
        .summary {{ color: {theme.text_secondary}; margin: 0 0 24px; }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 12px;
            margin: 24px 0 30px;
        }}
        .stat-card {{
            background: {theme.bg_secondary};
            border: 1px solid {theme.border};
            border-radius: 8px;
            padding: 18px;
        }}
        .stat-value {{ font-size: 30px; font-weight: 700; color: {theme.accent_primary}; }}
        .stat-label {{ color: {theme.text_muted}; margin-top: 4px; font-size: 13px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 14px 0 22px; }}
        th, td {{ padding: 11px 12px; text-align: left; border-bottom: 1px solid {theme.border}; }}
        th {{ background: {theme.bg_secondary}; color: {theme.text_secondary}; }}
        .bar {{ background: {theme.bg_tertiary}; height: 10px; border-radius: 999px; overflow: hidden; }}
        .bar-fill {{ background: {theme.accent_primary}; height: 100%; }}
        .footer {{ margin-top: 44px; color: {theme.text_muted}; text-align: center; font-size: 12px; }}
    </style>
</head>
<body>
    <main class="container">
        <div class="eyebrow">Analytics Export</div>
        <h1>Bookmark Analytics Report</h1>
        <p class="summary">Generated {html.escape(generated_at)} by {html.escape(self.app_name)}</p>

        <section class="stats-grid" aria-label="Summary">
            {self._stat_card("Total Bookmarks", _int_stat(stats, "total_bookmarks"))}
            {self._stat_card("Categories", _int_stat(stats, "total_categories"))}
            {self._stat_card("Tags", _int_stat(stats, "total_tags"))}
            {self._stat_card("Duplicates", _int_stat(stats, "duplicate_bookmarks"))}
        </section>

        <h2>Categories</h2>
        <table>
            <tr><th>Category</th><th>Count</th><th>Distribution</th></tr>
            {category_rows}
        </table>

        <h2>Top Domains</h2>
        <table>
            <tr><th>Domain</th><th>Count</th></tr>
            {domain_rows}
        </table>

        <h2>Age Distribution</h2>
        <table>
            <tr><th>Period</th><th>Count</th></tr>
            {age_rows}
        </table>

        <div class="footer">Generated by {html.escape(self.app_name)} {html.escape(self.app_version)}</div>
    </main>
</body>
</html>
"""
        _atomic_text_write(Path(filepath), document)

    def generate_text_report(self, filepath: str) -> None:
        """Generate a plain text analytics report."""
        stats = self.bookmark_manager.get_statistics()
        lines = [
            "=" * 60,
            "BOOKMARK ANALYTICS REPORT",
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "=" * 60,
            "",
            "SUMMARY",
            "-" * 40,
            f"Total Bookmarks:  {_int_stat(stats, 'total_bookmarks')}",
            f"Categories:       {_int_stat(stats, 'total_categories')}",
            f"Tags:             {_int_stat(stats, 'total_tags')}",
            f"Duplicates:       {_int_stat(stats, 'duplicate_bookmarks')}",
            f"Broken Links:     {_int_stat(stats, 'broken')}",
            f"Uncategorized:    {_int_stat(stats, 'uncategorized')}",
            "",
            "CATEGORIES",
            "-" * 40,
        ]

        for category, count in _sorted_counts(stats.get("category_counts", {})):
            lines.append(f"  {str(category)[:40]:40} {int(count or 0):5}")

        lines.extend(["", "TOP DOMAINS", "-" * 40])
        for domain, count in _sequence_counts(stats.get("top_domains", []))[:15]:
            lines.append(f"  {str(domain)[:40]:40} {int(count or 0):5}")

        lines.extend(["", "=" * 60, f"Generated by {self.app_name} {self.app_version}"])
        _atomic_text_write(Path(filepath), "\n".join(lines))

    def _category_row(self, category: object, count: object, total: int) -> str:
        count_int = int(count or 0)
        percentage = max(0.0, min(100.0, (count_int / total) * 100))
        return (
            "<tr>"
            f"<td>{html.escape(str(category))}</td>"
            f"<td>{count_int}</td>"
            "<td><div class=\"bar\">"
            f"<div class=\"bar-fill\" style=\"width: {percentage:.2f}%\"></div>"
            "</div></td>"
            "</tr>"
        )

    @staticmethod
    def _stat_card(label: str, value: int) -> str:
        return (
            "<article class=\"stat-card\">"
            f"<div class=\"stat-value\">{value}</div>"
            f"<div class=\"stat-label\">{html.escape(label)}</div>"
            "</article>"
        )


def _int_stat(stats: Mapping, key: str) -> int:
    try:
        return int(stats.get(key, 0) or 0)
    except (TypeError, ValueError):
        return 0


def _sorted_counts(values: object) -> Iterable[Tuple[object, int]]:
    if not isinstance(values, Mapping):
        return []
    return sorted(values.items(), key=lambda item: int(item[1] or 0), reverse=True)


def _sequence_counts(values: object) -> List[Tuple[object, int]]:
    result = []
    try:
        iterable = list(values)
    except TypeError:
        return result
    for item in iterable:
        if isinstance(item, (list, tuple)) and len(item) >= 2:
            result.append((item[0], int(item[1] or 0)))
    return result


def _atomic_text_write(filepath: Path, text: str) -> None:
    filepath.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_path = tempfile.mkstemp(dir=filepath.parent, suffix=".tmp", text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(temp_path, filepath)
    except Exception:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise
