"""Default categorization patterns across 32 categories.

Built from real-world bookmark analysis + top 3,000 websites research (Cloudflare Radar,
Similarweb, Tranco). 1,800+ domains with keyword fallbacks for long-tail coverage.
Pattern types supported: plain, domain:, keyword:, regex:, path:, title:.
"""

DEFAULT_CATEGORIES = {
    "Uncategorized / Needs Review": [
        "example.com", "example.org", "test.", "demo.", "staging."
    ],
    "Adult & Mature Content": [
        "pornhub.com", "xvideos.com", "xnxx.com", "xhamster.com", "redtube.com",
        "porn.", "xxx.", "chaturbate.com", "onlyfans.com", "fansly.com",
        "youporn.com", "tube8.com", "spankbang.com", "eporner.com",
        "motherless.com", "youjizz.com", "fuq.com", "nudevista.com",
        "domain:tabootube.xxx", "domain:filtradas.com",
        "domain:16ebalka.ru.actor", "domain:av4us.online",
        "domain:ins-dream.com",
        "keyword:porn", "keyword:xxx", "keyword:nsfw", "keyword:erotic",
        "keyword:incest", "keyword:onlyfans", "keyword:adult video",
    ],
    "Redirects, Trackers & Shorteners": [
        "domain:bit.ly", "domain:bitly.com", "domain:tinyurl.com",
        "domain:t.co", "domain:goo.gl", "domain:ow.ly",
        "domain:linktr.ee", "domain:linkin.bio",
        "domain:rebrand.ly", "domain:cutt.ly", "domain:is.gd",
        "domain:v.gd", "domain:shorturl.at",
        "domain:linkvertise.com", "domain:adf.ly", "domain:ouo.io",
        "redirect.", "tracking.", "click.",
        "utm_source=", "fbclid=", "gclid=", "mc_eid="
    ],
    "Internal Tools & Dashboards": [
        "localhost", "127.0.0.1", "192.168.", "10.0.", "172.16.", ".local",
        ".internal", ".lan", ":3000", ":8080", ":8443", ":9090", ":5000",
        "/admin", "/dashboard", "admin.", "dashboard.", "internal.", "intranet.",
        "domain:pfsense", "domain:opnsense", "domain:unifi"
    ],
    "Privacy & Security": [
        "domain:1password.com", "domain:lastpass.com", "domain:bitwarden.com",
        "domain:protonmail.com", "domain:proton.me", "domain:nordvpn.com",
        "domain:expressvpn.com", "domain:mullvad.net", "domain:torproject.org",
        "domain:signal.org", "domain:haveibeenpwned.com", "domain:privacyguides.org",
        "domain:privacytools.io", "domain:virustotal.com", "domain:keepassxc.org",
        "domain:tails.boum.org", "domain:whonix.org",
        "keyword:vpn", "keyword:privacy", "keyword:encrypt",
        "keyword:password manager", "keyword:two-factor", "keyword:2fa",
        "keyword:data breach", "keyword:identity theft",
    
        # Top-site expansion (top 3000 websites research)
        "domain:eff.org",
        "domain:epic.org",
        "domain:letsencrypt.org",
        "keyword:phishing",
        "keyword:ransomware",
        "keyword:zero-day",
        "keyword:penetration test",
    ],
    "Self-Hosted & Homelab": [
        "domain:pfsense.org", "domain:opnsense.org", "domain:proxmox.com",
        "domain:truenas.com", "domain:unraid.net", "domain:synology.com",
        "domain:home-assistant.io", "domain:jellyfin.org", "domain:plex.tv",
        "domain:sonarr.tv", "domain:radarr.video", "domain:nextcloud.com",
        "domain:pi-hole.net", "domain:portainer.io", "domain:emby.media",
        "domain:cockpit-project.org", "domain:homer-dashboard.com",
        "domain:wireguard.com", "domain:tailscale.com", "domain:zerotier.com",
        "domain:linuxserver.io", "domain:selfhosted.show",
        "domain:awesome-selfhosted.net", "domain:selfh.st",
        "domain:paperless-ngx.com", "domain:immich.app",
        "domain:freshrss.org", "domain:miniflux.app",
        "domain:vaultwarden.github.io", "domain:authelia.com",
        "keyword:self-hosted", "keyword:homelab", "keyword:home server",
        "keyword:docker compose", "keyword:media server",
    ],
    "SysAdmin & IT": [
        # Windows & Group Policy
        "domain:getadmx.com", "domain:admx.help", "domain:schneegans.de",
        "domain:winaero.com", "keyword:group policy", "keyword:gpedit",
        "keyword:admx", "keyword:unattend", "keyword:windows 10", "keyword:windows 11",
        "keyword:windows server", "keyword:powershell", "keyword:registry",
        "keyword:sccm", "keyword:intune", "keyword:wsus",
        "domain:go.microsoft.com", "domain:learn.microsoft.com",
        "domain:docs.microsoft.com", "domain:devblogs.microsoft.com",
        # Networking & DNS
        "domain:dnscheck.tools", "domain:mxtoolbox.com", "domain:whatismyip.com",
        "domain:dnschecker.org", "domain:dnsviz.net", "domain:ipchicken.com",
        "domain:whatsmydns.net", "domain:who.is", "domain:whois.com",
        "domain:speedtest.net", "domain:speakeasy.net", "domain:wifiman.com",
        "keyword:speed test", "keyword:dns", "keyword:whois",
        # Hardware & Drivers
        "domain:dell.com", "domain:hp.com", "domain:lenovo.com",
        "domain:intel.com", "domain:amd.com", "domain:nvidia.com",
        "domain:toshiba.com", "domain:gsmarena.com", "domain:amcrest.com",
        "domain:tomshardware.com", "domain:anandtech.com", "domain:pcpartpicker.com",
        # IT Forums & Resources
        "domain:tenforums.com", "domain:elevenforum.com", "domain:serverfault.com",
        "domain:spiceworks.com", "domain:ghacks.net", "domain:askwoody.com",
        "domain:howtogeek.com", "domain:techrepublic.com",
        "domain:windowscentral.com", "domain:neowin.net", "domain:theregister.com",
        "domain:computerworld.com", "domain:bleepingcomputer.com",
        # Remote Access & Management
        "domain:splashtop.com", "domain:screenconnect.com", "domain:connectwise.com",
        "domain:ninjaone.com", "domain:pdq.com", "domain:teamviewer.com",
        "domain:anydesk.com", "domain:remotedesktop.google.com",
        "domain:sync.com", "domain:info.easyvista.com", "domain:easyvista.com",
        "domain:teamlogicit.com", "domain:tech-keys.com",
        "domain:nexttechconsultants.com",
        # Status pages
        "domain:cloudflarestatus.com", "domain:status.microsoft", "domain:azure.status.microsoft",
        "domain:status.github.com", "domain:status.digitalocean.com",
        "domain:githubstatus.com", "domain:downdetector.com",
        # Microsoft ecosystem
        "domain:login.microsoftonline.com", "domain:microsoftonline.com",
        "domain:answers.microsoft.com", "domain:support.microsoft.com",
        "domain:technet.microsoft.com", "domain:developer.microsoft.com",
        "domain:security.microsoft.com", "domain:apps.microsoft.com",
        "domain:microsoft.com",
        # Image tools (sysadmin uses for processing)
        "domain:imagemagick.org", "domain:joesandbox.com",
        "domain:any.run", "domain:urlscan.io",
        # Customization tools
        "domain:wincustomize.com",
        # Networking / enterprise vendors
        "domain:cisco.com", "domain:juniper.net", "domain:arubanetworks.com",
        "domain:ubnt.com", "domain:ubiquiti.com", "domain:mikrotik.com",
        "domain:fortinet.com", "domain:sonicwall.com", "domain:sophos.com",
        "domain:meraki.com",
        "domain:netadmintools.com", "domain:carbonite.com",
        "domain:osticket.com", "domain:palmtreeit.org",
        "domain:myersinfosys.com", "domain:sysadminpedia.com",
        # Home networking
        "domain:myhomenetwork.att.com", "domain:att.com", "domain:xfinity.com",
        "domain:spectrum.com", "domain:comcast.com", "domain:cox.com",
        # SysAdmin tools (Windows)
        "domain:nirsoft.net", "domain:ntlite.com",
        "domain:autoitscript.com", "domain:autohotkey.com",
        "domain:winutil.christitus.com", "domain:christitus.com",
        "domain:marticliment.com",  # UniGetUI
        "domain:uninstalr.com", "domain:pete.akeo.ie",  # Rufus
        "domain:abelhadigital.com",  # HostsMan
        "domain:custopack.com", "domain:librewolf.net",
        "domain:spicetify.app",
        "domain:process-hacker.com", "domain:processhacker.sourceforge.io",
        "domain:sysinternals.com", "domain:live.sysinternals.com",
        # Meeting / remote support
        "domain:zoom.us", "domain:zoomgov.com", "domain:webex.com",
        "domain:gotomeeting.com", "domain:bluejeans.com",
        "domain:logmein.com", "domain:gotoassist.com",
        "domain:dualmon.com",
        # IT training / cheat sheets
        "domain:gfi.com", "domain:sysadmincasts.com", "domain:gestaltit.com",
        "domain:9tut.com", "domain:examcollection.com", "domain:avanset.com",
        # IT forums / utilities
        "domain:forum.avast.com", "domain:avast.com",
        "domain:icoconverter.com", "domain:mdl-tb.ct8.pl",
        # Enterprise software
        "domain:avid.force.com", "domain:ricoh-usa.com", "domain:ricoh.com",
        "domain:xerox.com", "domain:canon.com", "domain:brother.com",
        # Accounts / auth
        "domain:accounts.bdrive.com", "domain:bdrive.com",
        # File sharing / storage / backup (sysadmin context)
        "domain:wetransfer.com", "domain:sendspace.com",
        "domain:box.net", "domain:box.com", "domain:wuala.com",
        "domain:ammyy.com", "domain:airdroid.com", "domain:web.airdroid.com",
        "domain:dragshare.com", "domain:whatbox.ca", "domain:whatbox.com",
        "domain:hetzner.com", "domain:hetzner.online",
        "domain:ovhcloud.com", "domain:ovh.com",
        "domain:vultr.com", "domain:linode.com",
        # pfSense / security hardware
        "domain:netgate.com", "domain:pfsense.com",
        # Printer / hardware vendors
        "domain:global-print-driver.com", "domain:xerox.com",
        "domain:hp.com", "domain:epson.com", "domain:brother.com",
        # Other SysAdmin resources / utilities
        "domain:ez.lol",  # browser ID/extension tester
        "keyword:managed it", "keyword:it services", "keyword:it support",
        "keyword:endpoint", "keyword:patch management", "keyword:rmm",
        "keyword:active directory", "keyword:ldap", "keyword:dhcp",
        "keyword:firewall", "keyword:vlan", "keyword:subnet",
        "keyword:bitlocker", "keyword:tpm", "keyword:uefi", "keyword:bios",
        "keyword:virtualbox", "keyword:hyper-v", "keyword:vmware",
        "keyword:remote desktop", "keyword:remote admin", "keyword:remote control",
        "keyword:web hosting", "keyword:vps", "keyword:dedicated server",
        "keyword:backup solution", "keyword:file sharing",
        "keyword:cloud storage", "keyword:data backup",
        "keyword:virtual machine", "keyword:vm image",
        "keyword:pfsense", "keyword:opnsense", "keyword:netgate",
        "keyword:print driver", "keyword:printer setup",
    ],
    "Development & Programming": [
        # Code Hosting
        "domain:github.com", "domain:gitlab.com", "domain:bitbucket.org",
        "domain:codeberg.org", "domain:sourceforge.net",
        "domain:gist.github.com", "domain:raw.githubusercontent.com",
        # Q&A & Community
        "domain:stackoverflow.com", "domain:stackexchange.com",
        "domain:superuser.com", "domain:serverfault.com", "domain:dev.to",
        # IDEs & Playgrounds
        "domain:codepen.io", "domain:jsfiddle.net", "domain:replit.com",
        "domain:codesandbox.io", "domain:stackblitz.com",
        # Package Managers
        "domain:npmjs.com", "domain:pypi.org", "domain:crates.io",
        "domain:packagist.org", "domain:rubygems.org", "domain:nuget.org",
        # Competitive
        "domain:hackerrank.com", "domain:leetcode.com", "domain:codeforces.com",
        # Documentation
        "domain:developer.mozilla.org", "domain:w3schools.com",
        "domain:css-tricks.com", "domain:smashingmagazine.com",
        # Userscripts & Extensions
        "domain:greasyfork.org", "domain:openuserjs.org",
        "domain:userstyles.world", "domain:userstyles.org", "domain:userscripts.org",
        "domain:chromewebstore.google.com", "domain:addons.mozilla.org",
        "domain:uso.kkx.one",
        # Web Development
        "domain:themeforest.net", "domain:tailwindcss.com",
        "domain:vercel.com", "domain:netlify.com", "domain:heroku.com",
        # Dev Tools
        "domain:regex101.com", "domain:jsonformatter.org",
        "domain:producthunt.com", "domain:pastebin.com",
        "domain:community.chocolatey.org", "domain:chocolatey.org",
        "domain:winget.run", "domain:xda-developers.com",
        "domain:play.google.com",
        "domain:chrome.google.com",  # Chrome Web Store (old URL)
        # User's own / tools
        "domain:sysadmindoc.github.io",
        "domain:discuss.ipfs.tech", "domain:ipfs.io", "domain:ipfs.tech",
        "domain:someonewhocares.org",
        "domain:scrapy.org", "domain:remotion.dev",
        "domain:github.developerdan.com",
        "domain:tools.thatwind.com",
        "domain:chrome-stats.com", "domain:crxextractor.com",
        "domain:allpurposedesigns.com",
        "domain:a.dove.isdumb.one",
        "domain:massgrave.dev",
        "domain:console.firebase.google.com", "domain:firebase.google.com",
        # More IDEs / playgrounds
        "domain:glitch.com", "domain:observablehq.com", "domain:runkit.com",
        "domain:pythonanywhere.com", "domain:colab.google",
        # More docs
        "domain:readthedocs.io", "domain:readthedocs.org",
        "domain:godoc.org", "domain:pkg.go.dev",
        # API testing
        "domain:postman.com", "domain:insomnia.rest", "domain:httpbin.org",
        # Additional dev platforms / services
        "domain:supabase.com", "domain:expo.dev", "domain:go.dev",
        "domain:reactbits.dev", "domain:hlsjs.video-dev.org", "domain:video-dev.org",
        "domain:developertoolkits.com",
        # Online tools (dev-oriented)
        "domain:zamzar.com", "domain:textcleaner.net",
        "domain:base64-image.de", "domain:base64.guru",
        "domain:jsonlint.com", "domain:jsonformatter.curiousconcept.com",
        "domain:crontab.guru", "domain:explainshell.com",
        "domain:caniuse.com", "domain:devdocs.io", "domain:devhints.io",
        "domain:tldr.sh", "domain:tldr.inbrowser.app",
        # Dev blogs / personal dev sites
        "domain:vikash.nl", "domain:helloacm.com",
        "domain:blog.bahraniapps.com", "domain:bahraniapps.com",
        "domain:proggblo.blogspot.com",
        # Sysadmin scripting / extensions
        "domain:pro.sorrywatermark.com",
        # Game server / bot hosting
        "domain:dyno.gg",
        "keyword:userscript", "keyword:tampermonkey", "keyword:greasemonkey",
        "keyword:api documentation", "keyword:sdk", "keyword:github repo",
        "keyword:pull request", "keyword:pry request",
        "keyword:npm package", "keyword:pip install",
        "keyword:source code", "keyword:open source",
        "keyword:changelog", "keyword:release notes",
        "keyword:bug report", "keyword:issue tracker",
        "keyword:code snippet", "keyword:boilerplate",
        "keyword:framework", "keyword:library",
    
        # Top-site expansion (top 3000 websites research)
        "domain:python.org",
        "domain:nodejs.org",
        "domain:php.net",
        "domain:ruby-lang.org",
        "domain:rust-lang.org",
        "domain:typescriptlang.org",
        "domain:kotlinlang.org",
        "domain:swift.org",
        "domain:dotnet.microsoft.com",
        "domain:docker.com",
        "domain:jetbrains.com",
        "domain:unity3d.com",
        "domain:eclipse.org",
        "domain:code.visualstudio.com",
        "domain:git-scm.com",
        "domain:sublimetext.com",
        "domain:neovim.io",
        "domain:cdn.jsdelivr.net",
        "domain:cdnjs.cloudflare.com",
        "domain:anaconda.com",
        "domain:acm.org",
        "domain:spectrum.ieee.org",
        "domain:web.dev",
        "domain:material.io",
        "domain:unrealengine.com",
        "domain:godotengine.org",
        "domain:rapidapi.com",
        "domain:swagger.io",
        "domain:graphql.org",
        "keyword:code review",
        "keyword:git commit",
        "keyword:docker container",
        "keyword:kubernetes pod",
    ],
    "AI & Machine Learning": [
        # AI Assistants
        "domain:openai.com", "domain:anthropic.com", "domain:claude.ai",
        "domain:status.claude.com", "domain:chatgpt.com", "domain:chat.openai.com",
        "domain:gemini.google.com", "domain:aistudio.google.com", "domain:labs.google",
        "domain:poe.com", "domain:perplexity.ai", "domain:deepseek.com",
        "domain:chat.deepseek.com", "domain:copilot.microsoft.com",
        "domain:pi.ai", "domain:character.ai", "domain:chub.ai",
        "domain:chat.qwen.ai",
        # AI Development
        "domain:huggingface.co", "domain:kaggle.com",
        "domain:tensorflow.org", "domain:pytorch.org",
        "domain:colab.research.google.com", "domain:replicate.com",
        "domain:ollama.com", "domain:lmstudio.ai", "domain:cursor.com",
        "domain:cursor.sh", "domain:codeium.com", "domain:together.ai",
        "domain:groq.com", "domain:cohere.com", "domain:mistral.ai",
        "domain:ai.google.dev", "domain:console.anthropic.com",
        "domain:docs.anthropic.com", "domain:n8n.io",
        # AI Art & Media
        "domain:midjourney.com", "domain:stability.ai", "domain:civitai.com",
        "domain:suno.com", "domain:suno.ai", "domain:udio.com",
        "domain:elevenlabs.io", "domain:runwayml.com", "domain:kaiber.ai",
        "domain:leonardo.ai", "domain:ideogram.ai", "domain:pika.art",
        "domain:luma.ai", "domain:dreamstudio.ai", "domain:clipdrop.co",
        "domain:nightcafe.studio", "domain:heygen.com", "domain:murf.ai",
        "domain:hailuoai.video", "domain:napkin.ai",
        "domain:grok.com", "domain:grok.x.ai", "domain:x.ai",
        "domain:notebooklm.google.com", "domain:openrouter.ai",
        "domain:ink.trimythic.co", "domain:tattoosai.com",
        "domain:app.klingai.com", "domain:klingai.com",
        "domain:hailuo-02.com", "domain:minimax.io",
        "domain:stoat.chat", "domain:geminivideo.studio",
        "domain:prompts.chat", "domain:bitlife.ai",
        "domain:otter.ai", "domain:lenso.ai", "domain:copyseeker.net",
        "domain:apollo.io", "domain:jeneratex.com",
        "domain:app.patientimage.ai", "domain:app.vivalabs.ai",
        "domain:jobo.world", "domain:app.bio.link",
        "domain:tunemymusic.com", "domain:photopea.com",
        "domain:gab.ai", "domain:freedom-gpt.com",
        "domain:venice.ai", "domain:agnai.chat",
        "domain:you.com", "domain:phind.com",
        "domain:tldraw.com", "domain:cody.ai",
        "domain:tabnine.com", "domain:continue.dev",
        "keyword:ai model", "keyword:llm", "keyword:large language",
        "keyword:machine learning", "keyword:deep learning",
        "keyword:ai generator", "keyword:ai video", "keyword:ai image",
        "keyword:ai tool", "keyword:ai chatbot", "keyword:ai assistant",
        "keyword:prompt engineering", "keyword:fine-tuning",
    
        # Top-site expansion (top 3000 websites research)
        "domain:meta.ai",
        "domain:copilot.github.com",
        "domain:beta.openai.com",
        "domain:platform.openai.com",
        "domain:paperswithcode.com",
        "domain:wandb.ai",
        "domain:roboflow.com",
        "domain:scale.com",
        "keyword:transformer model",
        "keyword:neural network",
        "keyword:text-to-image",
        "keyword:text-to-video",
        "keyword:stable diffusion",
    ],
    "Cloud & Infrastructure": [
        "domain:aws.amazon.com", "domain:console.aws.amazon.com",
        "domain:azure.microsoft.com", "domain:portal.azure.com",
        "domain:cloud.google.com", "domain:digitalocean.com",
        "domain:linode.com", "domain:vultr.com", "domain:hetzner.com",
        "domain:cloudflare.com", "domain:dash.cloudflare.com",
        "domain:namecheap.com", "domain:godaddy.com", "domain:domains.google.com",
        "domain:squarespace.com", "domain:wordpress.com", "domain:wordpress.org",
        "domain:cpanel.com", "domain:one.com", "domain:siteground.com",
        "domain:hostinger.com", "domain:bluehost.com", "domain:dreamhost.com",
        "keyword:docker", "keyword:kubernetes", "keyword:terraform",
        "keyword:ansible", "keyword:vmware", "keyword:esxi", "keyword:proxmox",
        "keyword:aws", "keyword:azure", "keyword:cloud hosting",
        "keyword:cdn", "keyword:ssl certificate", "keyword:domain name",
    
        # Top-site expansion (top 3000 websites research)
        "domain:render.com",
        "domain:fly.io",
        "domain:fastly.com",
        "domain:akamai.com",
        "domain:terraform.io",
        "domain:ansible.com",
        "domain:datadog.com",
        "domain:newrelic.com",
        "domain:splunk.com",
        "domain:elastic.co",
        "domain:grafana.com",
        "domain:prometheus.io",
        "keyword:serverless",
        "keyword:microservice",
        "keyword:load balancer",
        "keyword:ci/cd",
        "keyword:devops",
    ],
    "News & Media": [
        "domain:cnn.com", "domain:bbc.com", "domain:bbc.co.uk",
        "domain:reuters.com", "domain:apnews.com", "domain:nytimes.com",
        "domain:washingtonpost.com", "domain:theguardian.com",
        "domain:bloomberg.com", "domain:techcrunch.com",
        "domain:foxnews.com", "domain:nbcnews.com", "domain:cbsnews.com",
        "domain:abcnews.go.com", "domain:npr.org", "domain:usatoday.com",
        "domain:latimes.com", "domain:nypost.com", "domain:msn.com",
        "domain:news.google.com", "domain:news.ycombinator.com",
        "domain:breitbart.com", "domain:dailymail.co.uk", "domain:zerohedge.com",
        "domain:infowars.com", "domain:newsmax.com", "domain:theblaze.com",
        "domain:drudgereport.com", "domain:revolver.news",
        "domain:thegatewaypundit.com", "domain:americanthinker.com",
        "domain:theverge.com", "domain:wired.com", "domain:engadget.com",
        "domain:vice.com", "domain:vox.com", "domain:slate.com",
        "domain:salon.com", "domain:huffpost.com", "domain:politico.com",
        "domain:thehill.com", "domain:axios.com", "domain:mashable.com",
        "domain:thedailybeast.com", "domain:medium.com", "domain:substack.com",
        "domain:libertylinks.io",
        # Local news / regional
        "domain:whio.com", "domain:whiotv.com",
        "domain:thinktv.org", "domain:downtowndayton.org",
        # Alternative / political
        "domain:infogalactic.com", "domain:bellingcat.gitbook.io", "domain:bellingcat.com",
        "domain:dailywire.com", "domain:mises.org",
        "domain:frontier.com", "domain:theepochtimes.com", "domain:theconservativetreehouse.com",
        "domain:zerohedge.com", "domain:citizenfreepress.com",
        # Science / education news
        "domain:nuclearsecrecy.com", "domain:sciencedaily.com",
        "domain:phys.org", "domain:space.com",
        "domain:arstechnica.com", "domain:hackernoon.com",
        # General interest / lifestyle
        "domain:lifehacker.com", "domain:buzzfeed.com",
        "domain:ted.com", "domain:goodreads.com",
        "domain:atlasobscura.com", "domain:bigthink.com",
        "domain:aeon.co", "domain:nautil.us",
        # Personal blogs / authors (common unknown)
        "domain:todaywillbedifferent.com",
        "domain:brittanyanneauthor.com",
        # Podcast / newsletter platforms (news context)
        "domain:rss.com", "domain:feedburner.google.com",
        # Additional news keywords
        "keyword:breaking news", "keyword:headlines",
        "keyword:press release", "keyword:editorial",
        "keyword:opinion piece", "keyword:investigat",
        "keyword:latest news", "keyword:news update",
    
        # Top-site expansion (top 3000 websites research)
        "domain:forbes.com",
        "domain:fortune.com",
        "domain:businessinsider.com",
        "domain:economist.com",
        "domain:time.com",
        "domain:wsj.com",
        "domain:ft.com",
        "domain:fastcompany.com",
        "domain:inc.com",
        "domain:newyorker.com",
        "domain:vanityfair.com",
        "domain:variety.com",
        "domain:hollywoodreporter.com",
        "domain:rollingstone.com",
        "domain:billboard.com",
        "domain:smithsonianmag.com",
        "domain:nationalgeographic.com",
        "domain:pbs.org",
        "domain:aljazeera.com",
        "domain:france24.com",
        "domain:dw.com",
        "domain:rt.com",
        "domain:globalnews.ca",
        "domain:cbc.ca",
        "domain:abc.net.au",
        "domain:timesofindia.indiatimes.com",
        "domain:japantimes.co.jp",
        "domain:scmp.com",
        "domain:straitstimes.com",
        "domain:independent.co.uk",
        "domain:telegraph.co.uk",
        "domain:thetimes.co.uk",
        "domain:metro.co.uk",
        "domain:thesun.co.uk",
        "domain:mirror.co.uk",
        "domain:sfgate.com",
        "domain:chicagotribune.com",
        "domain:denverpost.com",
        "domain:nydailynews.com",
        "domain:prnewswire.com",
        "domain:businesswire.com",
        "domain:propublica.org",
        "domain:digitaltrends.com",
        "domain:9to5mac.com",
        "domain:androidauthority.com",
        "domain:makeuseof.com",
        "domain:zdnet.com",
        "domain:adweek.com",
        "domain:adage.com",
        "domain:digiday.com",
        "domain:pewresearch.org",
        "domain:statista.com",
        "domain:qz.com",
        "domain:boredpanda.com",
        "domain:ranker.com",
        "domain:flipboard.com",
        "domain:globo.com",
        "domain:repubblica.it",
        "domain:lemonde.fr",
        "domain:spiegel.de",
        "domain:bild.de",
        "domain:faz.net",
        "domain:zeit.de",
        "domain:lefigaro.fr",
        "domain:ouest-france.fr",
        "domain:leparisien.fr",
        "domain:elmundo.es",
        "domain:rtve.es",
        "keyword:newspaper",
        "keyword:journalist",
        "keyword:media outlet",
    ],
    "Weather & Meteorology": [
        "domain:weather.com", "domain:weather.gov", "domain:noaa.gov",
        "domain:nhc.noaa.gov", "domain:star.nesdis.noaa.gov",
        "domain:tropicaltidbits.com", "domain:wunderground.com",
        "domain:accuweather.com", "domain:windy.com", "domain:ventusky.com",
        "domain:earth.nullschool.net", "domain:zoom.earth",
        "domain:lightningmaps.org", "domain:spaghettimodels.com",
        "domain:rammb-slider.cira.colostate.edu", "domain:cira.colostate.edu",
        "domain:web.weatherwise.app", "domain:weatherwise.app",
        "domain:staticbaronwebapps.velocityweather.com", "domain:velocityweather.com",
        "domain:s.w-x.co", "domain:w-x.co",
        "domain:pivotalweather.com", "domain:mrx.com",
        "domain:stormtrack.org", "domain:aviationweather.gov",
        "keyword:weather", "keyword:forecast", "keyword:hurricane",
        "keyword:tropical storm", "keyword:tornado", "keyword:radar",
        "keyword:doppler", "keyword:severe weather",
    ],
    "Social Media": [
        "domain:twitter.com", "domain:x.com", "domain:nitter.net",
        "domain:facebook.com", "domain:m.facebook.com", "domain:fb.com",
        "domain:instagram.com", "domain:linkedin.com",
        "domain:tiktok.com", "domain:pinterest.com", "domain:tumblr.com",
        "domain:snapchat.com", "domain:threads.net",
        "domain:bluesky.app", "domain:bsky.app",
        "domain:mastodon.social", "domain:nextdoor.com",
        # Messaging / chat
        "domain:whatsapp.com", "domain:web.whatsapp.com",
        "domain:web.telegram.org", "domain:signal.org",
        # Photo / video social
        "domain:flickr.com", "domain:500px.com", "domain:vsco.co",
        "domain:lemon8-app.com", "domain:bereal.com",
        # Niche social
        "domain:reddit.com/user", "domain:about.me",
        "domain:linktree.com", "domain:linktr.ee",
        "domain:carrd.co", "domain:bio.link",
        # Keywords
        "keyword:social media", "keyword:followers", "keyword:influencer",
        "keyword:social network",
    
        # Top-site expansion (top 3000 websites research)
        "domain:telegram.me",
        "domain:ok.ru",
        "domain:weibo.com",
        "domain:line.me",
        "domain:zalo.me",
        "domain:gravatar.com",
        "domain:meetup.com",
        "domain:eventbrite.com",
        "domain:clubhouse.com",
        "domain:wattpad.com",
    ],
    "Forums & Communities": [
        "domain:reddit.com", "domain:old.reddit.com", "domain:new.reddit.com",
        "domain:quora.com", "domain:discord.com", "domain:discord.gg",
        "domain:slack.com", "domain:telegram.org", "domain:t.me",
        "domain:boards.4chan.org", "domain:boards.4channel.org",
        "domain:4chan.org", "domain:4channel.org",
        "domain:godlikeproductions.com",
        "domain:forums.somethingawful.com", "domain:somethingawful.com",
        "domain:kiwifarms.net", "domain:imgur.com",
        "domain:voat.co", "domain:scored.co", "domain:communities.win",
        "domain:gab.com", "domain:truthsocial.com", "domain:minds.com",
        "domain:parler.com", "domain:gettr.com", "domain:ruqqus.com",
        "domain:8ch.net", "domain:8kun.top",
        "domain:patriots.win", "domain:communities.win",
        "domain:kiwifarms.st", "domain:kiwifarms.net",
        "domain:16chan.xyz", "domain:16chan.to",
        "domain:ar15.com", "domain:thehighroad.org",
        "domain:forum.aprelteam.su", "domain:aprelteam.su",
        # Additional forum / community platforms
        "domain:twitch.tv/directory", "domain:vk.com",
        "domain:tapatalk.com", "domain:proboards.com",
        "domain:forums.redflagdeals.com", "domain:slickdeals.net",
        "keyword:discussion forum", "keyword:subreddit",
        "keyword:community", "keyword:message board",
        "keyword:comments", "keyword:thread",
    
        # Top-site expansion (top 3000 websites research)
        "domain:fandom.com",
        "domain:namu.wiki",
        "domain:disqus.com",
        "domain:boardgamegeek.com",
        "domain:ravelry.com",
        "domain:instructables.com",
        "domain:warriorforum.com",
        "domain:bitcointalk.org",
        "domain:discogs.com",
        "domain:bandsintown.com",
        "keyword:forum post",
        "keyword:board topic",
    ],
    "Shopping & E-commerce": [
        "domain:amazon.com", "domain:smile.amazon.com", "domain:camelcamelcamel.com",
        "domain:ebay.com", "domain:walmart.com", "domain:target.com",
        "domain:bestbuy.com", "domain:etsy.com", "domain:aliexpress.com",
        "domain:shopify.com", "domain:newegg.com", "domain:bhphotovideo.com",
        "domain:wish.com", "domain:temu.com", "domain:shein.com",
        "domain:wayfair.com", "domain:homedepot.com", "domain:lowes.com",
        "domain:costco.com", "domain:samsclub.com", "domain:ikea.com",
        "domain:overstock.com", "domain:menards.com", "domain:harborfreight.com",
        "domain:monoprice.com", "domain:kohls.com", "domain:macys.com",
        "domain:nordstrom.com", "domain:zappos.com",
        "domain:craigslist.org", "domain:offerup.com", "domain:mercari.com",
        "domain:poshmark.com", "domain:swappa.com",
        "domain:fedex.com", "domain:ups.com", "domain:usps.com",
        "domain:cvs.com", "domain:walgreens.com",
        # Firearms & Outdoor
        "domain:gunbroker.com", "domain:guns.com", "domain:impactguns.com",
        "domain:palmettostatearmory.com", "domain:budsgunshop.com",
        "domain:classicfirearms.com", "domain:ammoseek.com",
        "domain:midwayusa.com", "domain:brownells.com",
        "domain:cheaperthandirt.com", "domain:sportsmansguide.com",
        "domain:truegunvalue.com", "domain:springfield-armory.com",
        "domain:rei.com", "domain:bassproshops.com", "domain:cabelas.com",
        "domain:dickssportinggoods.com",
        # Outdoor / clothing
        "domain:kuhl.com", "domain:patagonia.com", "domain:northface.com",
        "domain:columbia.com",
        # Home furnishings
        "domain:thefurniturewarehouse.com", "domain:firebox.com",
        "domain:beautyrest.com", "domain:secretlab.co",
        # Storage
        "domain:myaccount.extraspace.com", "domain:extraspace.com",
        "domain:publicstorage.com", "domain:cubesmart.com",
        # Misc specialty
        "domain:laserpointerpro.com", "domain:woodhullusa.com",
        "domain:northerner.com", "domain:drizly.com",
        "domain:zero.com",
        # Tobacco / vape
        "domain:gotsmoke.com", "domain:smokershub.com",
        "keyword:firearm", "keyword:ammo", "keyword:holster",
        "keyword:for sale", "keyword:buy online", "keyword:discount",
        "keyword:coupon", "keyword:promo code", "keyword:deal",
        "keyword:price compare", "keyword:free shipping",
        "keyword:add to cart", "keyword:checkout",
        "keyword:order tracking", "keyword:returns policy",
    
        # Top-site expansion (top 3000 websites research)
        "domain:alibaba.com",
        "domain:rakuten.co.jp",
        "domain:asos.com",
        "domain:zara.com",
        "domain:hm.com",
        "domain:gap.com",
        "domain:uniqlo.com",
        "domain:nike.com",
        "domain:adidas.com",
        "domain:underarmour.com",
        "domain:lululemon.com",
        "domain:newbalance.com",
        "domain:sephora.com",
        "domain:ulta.com",
        "domain:bathandbodyworks.com",
        "domain:chewy.com",
        "domain:petco.com",
        "domain:petsmart.com",
        "domain:staples.com",
        "domain:officedepot.com",
        "domain:barnesandnoble.com",
        "domain:bookshop.org",
        "domain:abebooks.com",
        "domain:retailmenot.com",
        "domain:honey.com",
        "domain:trustpilot.com",
        "domain:bbb.org",
        "keyword:order status",
        "keyword:shopping cart",
        "keyword:wish list",
        "keyword:product review",
        "keyword:compare prices",
        "keyword:best deal",
    ],
    "Entertainment & Streaming": [
        # Video Streaming
        "domain:youtube.com", "domain:youtu.be", "domain:music.youtube.com",
        "domain:netflix.com", "domain:hulu.com", "domain:disneyplus.com",
        "domain:hbomax.com", "domain:max.com", "domain:primevideo.com",
        "domain:peacocktv.com", "domain:paramountplus.com",
        "domain:pluto.tv", "domain:tubi.tv", "domain:crackle.com",
        "domain:vudu.com", "domain:dailymotion.com", "domain:vimeo.com",
        # Live Streaming
        "domain:twitch.tv", "domain:kick.com", "domain:rumble.com",
        "domain:fishtank.live", "domain:dlive.tv", "domain:trovo.live",
        "domain:bitwave.tv", "domain:censored.tv", "domain:cozy.tv",
        "domain:bitchute.com", "domain:odysee.com", "domain:liveomg.com",
        "domain:putchannel.com", "domain:patreon.com",
        # Movies & TV
        "domain:imdb.com", "domain:rottentomatoes.com", "domain:letterboxd.com",
        "domain:justwatch.com", "domain:thetvdb.com", "domain:themoviedb.org",
        "domain:trakt.tv", "domain:abetterqueue.com",
        "domain:arc018.to", "domain:flixmomo.com",
        "domain:uflix.to", "domain:thetvapp.to",
        "domain:noodlemagazine.com", "domain:leonardaisfunny.com",
        "domain:metiix.com", "domain:godownloads.net",
        "domain:solarmoviez.ru", "domain:m4uhd.page",
        "domain:publiciptv.com", "domain:streamlicensing.com",
        "domain:stream2video.tv", "domain:usnewslive.tv",
        "domain:mysuncoast.com", "domain:southhemitv.com",
        "domain:americafirst.live", "domain:unauthorized.tv",
        "domain:banned.video", "domain:warroom.org", "domain:pandemic.warroom.org",
        "domain:ome.tv", "domain:chaturbate.com",
        # Professional streaming infrastructure
        "domain:dacast.com", "domain:brightcove.com", "domain:vimeo.com",
        "domain:storyblocks.com",
        "domain:myslingstudio.com", "domain:gatesair.com",
        "domain:kapwing.com", "domain:heroturko.me",
        "domain:downr.org", "domain:audfree.com",
        "domain:desktop.captions.ai", "domain:captions.ai",
        # Music & Audio
        "domain:spotify.com", "domain:open.spotify.com",
        "domain:soundcloud.com", "domain:bandcamp.com",
        "domain:last.fm", "domain:deezer.com", "domain:tidal.com",
        "domain:music.apple.com", "domain:distrokid.com",
        "domain:tothebestof.com", "domain:genius.com",
        "domain:tunetidy.com", "domain:cduniverse.com",
        "domain:crunchyroll.com",
        "domain:pandora.com", "domain:stereomood.com", "domain:relaxingbeats.com",
        "domain:artists.apple.com", "domain:getcoverify.com",
        "domain:getworkdonemusic.com", "domain:bensound.com",
        "domain:groovedrumming.com", "domain:myinstants.com",
        "domain:bertcast.com", "domain:toao.net",
        "domain:itunes.apple.com",
        # Music production / royalty-free
        "domain:looperman.com", "domain:splice.com",
        "domain:beatstars.com", "domain:freesound.org",
        "keyword:asmr", "keyword:playlist", "keyword:instrumental",
        # Podcasts
        "domain:podcasts.apple.com", "domain:overcast.fm",
        "domain:pocketcasts.com", "domain:castbox.fm",
        "domain:podbean.com", "domain:anchor.fm", "domain:buzzsprout.com",
        "domain:transistor.fm", "domain:simplecast.com",
        # Comics / manga / anime
        "domain:webtoons.com", "domain:mangadex.org", "domain:myanimelist.net",
        "domain:anilist.co", "domain:comixology.com",
        "keyword:podcast", "keyword:episode", "keyword:stream",
        "keyword:watch online", "keyword:movie", "keyword:tv show",
        "keyword:anime", "keyword:manga", "keyword:webtoon",
    
        # Top-site expansion (top 3000 websites research)
        "domain:apple.tv",
        "domain:fubo.tv",
        "domain:sling.com",
        "domain:philo.com",
        "domain:discoveryplus.com",
        "domain:mixcloud.com",
        "domain:audiomack.com",
        "domain:tunein.com",
        "domain:iheart.com",
        "domain:audible.com",
        "domain:tvtropes.org",
        "domain:giphy.com",
        "domain:tenor.com",
        "domain:9gag.com",
        "domain:knowyourmeme.com",
        "keyword:binge watch",
        "keyword:new season",
        "keyword:box office",
        "keyword:trailer",
        "keyword:soundtrack",
        "keyword:lyrics",
    ],
    "Gaming": [
        "domain:steam.com", "domain:steampowered.com", "domain:store.steampowered.com",
        "domain:epicgames.com", "domain:gog.com", "domain:itch.io",
        "domain:xbox.com", "domain:playstation.com", "domain:nintendo.com",
        "domain:ign.com", "domain:gamespot.com", "domain:pcgamer.com",
        "domain:kotaku.com", "domain:polygon.com",
        "domain:curseforge.com", "domain:modrinth.com", "domain:minecraft.net",
        "domain:mcprohosting.com", "domain:dev.bukkit.org",
        "domain:roblox.com", "domain:ea.com", "domain:ubisoft.com",
        "domain:crusaders.gg", "domain:battlefy.com",
        "domain:ea.sports", "domain:leagueoflegends.com",
        "domain:riotgames.com", "domain:blizzard.com",
        "domain:battle.net", "domain:bethesda.net",
        "domain:humblebundle.com", "domain:fanatical.com",
        "domain:gamivo.com", "domain:cdkeys.com", "domain:g2a.com",
        "domain:speedrun.com", "domain:twitchmetrics.net",
        "domain:howlongtobeat.com", "domain:backloggd.com",
        # Additional
        "domain:nexusmods.com", "domain:moddb.com", "domain:gamebanana.com",
        "domain:eurogamer.net", "domain:gamesradar.com", "domain:destructoid.com",
        "domain:rockpapershotgun.com", "domain:escapistmagazine.com",
        "domain:rawg.io", "domain:opencritic.com", "domain:metacritic.com",
        "domain:retrogames.cc", "domain:emulator.online",
        "keyword:game mod", "keyword:cheat code", "keyword:walkthrough",
        "keyword:gameplay", "keyword:esports", "keyword:game pass",
    
        # Top-site expansion (top 3000 websites research)
        "domain:steamdb.info",
        "domain:steamcharts.com",
        "domain:isthereanydeal.com",
        "domain:gg.deals",
        "domain:pcgamingwiki.com",
        "domain:igdb.com",
        "keyword:game save",
        "keyword:achievement",
        "keyword:leaderboard",
        "keyword:multiplayer",
    ],
    "Finance & Banking": [
        "domain:chase.com", "domain:bankofamerica.com", "domain:wellsfargo.com",
        "domain:paypal.com", "domain:venmo.com", "domain:robinhood.com",
        "domain:fidelity.com", "domain:coinbase.com", "domain:mint.com",
        "domain:creditkarma.com", "domain:turbotax.com",
        "domain:irs.gov", "domain:stripe.com", "domain:square.com",
        "domain:quickbooks.intuit.com", "domain:freshbooks.com",
        "domain:gusto.com", "domain:paylocity.com",
        # Credit unions / regional banks
        "domain:wpcuonline.net", "domain:wpcu.coop",
        "domain:achievacu.com", "domain:banking.achievacu.com",
        "domain:creditonebank.com", "domain:auth.tiaa.org", "domain:tiaa.org",
        "domain:suncoastcreditunion.com",
        "domain:pnc.com", "domain:usbank.com", "domain:citibank.com",
        "domain:capitalone.com", "domain:discover.com",
        "domain:ally.com", "domain:schwab.com", "domain:vanguard.com",
        "domain:kraken.com", "domain:binance.com", "domain:gemini.com",
        # Insurance (finance-adjacent)
        "domain:ecams.geico.com", "domain:geico.com",
        "domain:progressive.com", "domain:statefarm.com",
        "domain:allstate.com", "domain:usaa.com",
        "domain:manage.myassurantpolicy.com", "domain:assurant.com",
        # Crypto / stocks / finance data
        "domain:bitbo.io", "domain:coinmarketcap.com", "domain:coingecko.com",
        "domain:etherscan.io", "domain:blockchain.com",
        "domain:finviz.com", "domain:yahoo.com/finance",
        "domain:marketwatch.com", "domain:cnbc.com",
        "domain:nasdaq.com", "domain:seekingalpha.com",
        "domain:morningstar.com", "domain:investing.com",
        "keyword:credit union", "keyword:banking", "keyword:online banking",
        "keyword:brokerage", "keyword:investment", "keyword:insurance",
        "keyword:bitcoin price", "keyword:crypto", "keyword:ethereum",
        "keyword:stock price", "keyword:commodities", "keyword:oil price",
    
        # Top-site expansion (top 3000 websites research)
        "domain:wise.com",
        "domain:revolut.com",
        "domain:chime.com",
        "domain:sofi.com",
        "domain:wealthfront.com",
        "domain:betterment.com",
        "domain:etrade.com",
        "domain:ameritrade.com",
        "domain:tradingview.com",
        "domain:fool.com",
        "domain:nerdwallet.com",
        "domain:bankrate.com",
        "domain:annualcreditreport.com",
        "domain:treasury.gov",
        "keyword:stock market",
        "keyword:mutual fund",
        "keyword:credit score",
        "keyword:tax return",
        "keyword:401k",
        "keyword:budget",
        "keyword:loan",
        "keyword:interest rate",
        "keyword:refinance",
    ],
    "Education & Learning": [
        # MOOCs / online learning
        "domain:coursera.org", "domain:udemy.com", "domain:edx.org",
        "domain:khanacademy.org", "domain:udacity.com", "domain:codecademy.com",
        "domain:freecodecamp.org", "domain:duolingo.com", "domain:masterclass.com",
        "domain:pluralsight.com", "domain:skillshare.com", "domain:lynda.com",
        "domain:flatiron.com", "domain:brilliant.org", "domain:datacamp.com",
        "domain:treehouse.com", "domain:linkedin.com/learning",
        "domain:learning.linkedin.com",
        # Language learning
        "domain:babbel.com", "domain:busuu.com", "domain:memrise.com",
        "domain:rosettastone.com", "domain:italki.com",
        # Textbooks / study tools
        "domain:chegg.com", "domain:bartleby.com", "domain:studylib.net",
        "domain:quizlet.com", "domain:brainly.com", "domain:sparknotes.com",
        "domain:cliffsnotes.com", "domain:openstax.org",
        "domain:gutenberg.org", "domain:libgen.is", "domain:zlibrary.org",
        # University / .edu catch-all
        "regex:\\.edu(/|$)",
        "domain:mit.edu", "domain:stanford.edu", "domain:harvard.edu",
        "domain:cornell.edu", "domain:berkeley.edu",
        # K-12 / tutoring
        "domain:ixl.com", "domain:prodigygame.com", "domain:mathway.com",
        "domain:symbolab.com", "domain:desmos.com",
        "domain:wyzant.com", "domain:tutor.com",
        # Certification / professional
        "domain:comptia.org", "domain:cisco.com/c/en/us/training-events",
        "domain:aws.amazon.com/certification",
        "domain:testout.com", "domain:cbtnuggets.com",
        # Keywords
        "keyword:certification", "keyword:practice test",
        "keyword:comptia", "keyword:microsoft cert",
        "keyword:online course", "keyword:study guide",
        "keyword:learn ", "keyword:tutorial", "keyword:how to ",
        "keyword:textbook", "keyword:homework", "keyword:syllabus",
    
        # Top-site expansion (top 3000 websites research)
        "domain:scratch.mit.edu",
        "domain:ocw.mit.edu",
        "domain:instructure.com",
        "domain:blackboard.com",
        "domain:schoology.com",
        "domain:moodle.org",
        "domain:d2l.com",
        "domain:academia.edu",
        "domain:photomath.com",
        "domain:socratic.org",
        "domain:grammarly.com",
        "domain:turnitin.com",
        "keyword:e-learning",
        "keyword:mooc",
        "keyword:lecture notes",
        "keyword:exam prep",
        "keyword:flashcard",
    ],
    "Reference & Research": [
        "domain:wikipedia.org", "domain:en.wikipedia.org", "domain:britannica.com",
        "domain:merriam-webster.com", "domain:dictionary.com",
        "domain:scholar.google.com", "domain:arxiv.org", "domain:pubmed.gov",
        "domain:wolframalpha.com", "domain:archive.org", "domain:web.archive.org",
        "domain:biblegateway.com", "domain:quora.com",
        # Flight & Ship Tracking
        "domain:globe.airplanes.live", "domain:globe.adsbexchange.com",
        "domain:flightradar24.com", "domain:flightaware.com",
        "domain:planefinder.net", "domain:marinetraffic.com",
        "domain:vesselfinder.com",
        # Maps & Geo
        "domain:maps.google.com", "domain:openstreetmap.org",
        "domain:earth.google.com", "domain:darksitefinder.com",
        "domain:justicemap.org",
        "domain:arcgis.com", "domain:apps.sentinel-hub.com", "domain:sentinel-hub.com",
        "domain:mapautist.com", "domain:nuclearsecrecy.com",
        # Search engines
        "domain:duckduckgo.com", "domain:start.me",
        "domain:translate.google.com",
        "domain:startpage.com", "domain:kagi.com", "domain:brave.com",
        "domain:yandex.com", "domain:baidu.com",
        "domain:search.brave.com", "domain:qwant.com",
        "domain:ecosia.org", "domain:searxng.org",
        # Reference / encyclopedic
        "domain:infogalactic.com", "domain:wiktionary.org",
        "domain:thefreedictionary.com", "domain:vocabulary.com",
        "domain:snopes.com", "domain:factcheck.org",
        "domain:politifact.com", "domain:straightdope.com",
        "domain:tineye.com",  # reverse image search
        # User's generic Google account / profile
        "domain:myaccount.google.com", "domain:accounts.google.com",
        # Additional reference
        "domain:worldometers.info", "domain:numbeo.com",
        "domain:timeanddate.com", "domain:convertunits.com",
        "domain:unitconversion.org", "domain:calculator.net",
        "domain:stackexchange.com",
        "keyword:definition", "keyword:meaning of",
        "keyword:encyclopedia", "keyword:wiki", "keyword:lookup",
        "keyword:calculator", "keyword:converter", "keyword:translate",
    
        # Top-site expansion (top 3000 websites research)
        "domain:sciencedirect.com",
        "domain:nature.com",
        "domain:jstor.org",
        "domain:researchgate.net",
        "domain:pubmed.ncbi.nlm.nih.gov",
        "domain:ncbi.nlm.nih.gov",
        "domain:pnas.org",
        "domain:academic.oup.com",
        "domain:journals.sagepub.com",
        "domain:springer.com",
        "domain:link.springer.com",
        "domain:onlinelibrary.wiley.com",
        "domain:tandfonline.com",
        "domain:cell.com",
        "domain:bmj.com",
        "domain:nejm.org",
        "domain:thelancet.com",
        "domain:jamanetwork.com",
        "domain:doi.org",
        "domain:dx.doi.org",
        "domain:orcid.org",
        "domain:loc.gov",
        "domain:openlibrary.org",
        "domain:hathitrust.org",
        "domain:ssrn.com",
        "domain:etymonline.com",
        "domain:thesaurus.com",
        "domain:waze.com",
        "domain:mapbox.com",
        "keyword:peer review",
        "keyword:journal article",
        "keyword:academic paper",
        "keyword:scientific study",
        "keyword:citation",
        "keyword:bibliography",
    ],
    "Travel & Transportation": [
        "domain:booking.com", "domain:airbnb.com", "domain:expedia.com",
        "domain:kayak.com", "domain:tripadvisor.com", "domain:vrbo.com",
        "domain:hotels.com", "domain:hotwire.com", "domain:priceline.com",
        "domain:travelocity.com", "domain:orbitz.com",
        "domain:uber.com", "domain:lyft.com", "domain:skyscanner.com",
        "domain:southwest.com", "domain:united.com", "domain:delta.com",
        "domain:aa.com", "domain:allegiantair.com", "domain:spiritairlines.com",
        "domain:amtrak.com", "domain:greyhound.com",
        # Local / municipal (Florida / Ohio per user profile)
        "domain:venicegov.com", "domain:downtowndayton.org",
        "domain:fpl.com", "domain:duke-energy.com",
        # Additional travel
        "domain:hopper.com", "domain:trivago.com",
        "domain:ihg.com", "domain:marriott.com", "domain:hilton.com",
        "domain:hyatt.com", "domain:choicehotels.com",
        "domain:momondo.com", "domain:google.com/flights",
        # Car rental
        "domain:enterprise.com", "domain:hertz.com", "domain:avis.com",
        "domain:budget.com", "domain:nationalcar.com", "domain:turo.com",
        # Cruises
        "domain:royalcaribbean.com", "domain:carnival.com", "domain:ncl.com",
        "domain:princess.com", "domain:celebritycruises.com",
        # Public transit / rideshare
        "domain:transit.app", "domain:moovitapp.com",
        "keyword:flights to", "keyword:hotel booking",
        "keyword:road trip", "keyword:vacation rental",
        "keyword:travel guide", "keyword:cruise",
    
        # Top-site expansion (top 3000 websites research)
        "domain:agoda.com",
        "domain:hostelworld.com",
        "domain:rome2rio.com",
        "domain:thetrainline.com",
        "domain:flixbus.com",
        "domain:gasbuddy.com",
        "keyword:itinerary",
        "keyword:backpacking",
        "keyword:passport",
        "keyword:visa application",
    ],
    "Food & Dining": [
        # Delivery / ordering
        "domain:doordash.com", "domain:ubereats.com", "domain:grubhub.com",
        "domain:instacart.com", "domain:seamless.com", "domain:postmates.com",
        "domain:gopuff.com", "domain:hungryroot.com",
        # Reviews / reservations
        "domain:yelp.com", "domain:opentable.com", "domain:resy.com",
        "domain:tripadvisor.com/restaurants",
        # Recipes & cooking
        "domain:allrecipes.com", "domain:epicurious.com", "domain:food.com",
        "domain:foodnetwork.com", "domain:simplyrecipes.com",
        "domain:seriouseats.com", "domain:bonappetit.com",
        "domain:tasteodhome.com", "domain:delish.com",
        "domain:cookinglight.com", "domain:thekitchn.com",
        "domain:budgetbytes.com", "domain:skinnytaste.com",
        "domain:minimalistbaker.com", "domain:damndelicious.net",
        "domain:tasty.co", "domain:sallysbakingaddiction.com",
        # Grocery / meal kits
        "domain:kroger.com", "domain:publix.com", "domain:heb.com",
        "domain:safeway.com", "domain:albertsons.com", "domain:aldi.us",
        "domain:traderjoes.com", "domain:wegmans.com",
        "domain:hellofresh.com", "domain:blueapron.com",
        "domain:freshly.com", "domain:factor75.com",
        # Drinks
        "domain:untappd.com", "domain:vivino.com", "domain:totalwine.com",
        "domain:drizly.com", "domain:wine.com",
        # Fast food / chains
        "domain:mcdonalds.com", "domain:chipotle.com",
        "domain:chickfila.com", "domain:dominos.com", "domain:papajohns.com",
        "domain:starbucks.com", "domain:dunkindonuts.com",
        # Keywords
        "keyword:recipe", "keyword:restaurant", "keyword:cooking",
        "keyword:meal prep", "keyword:food delivery", "keyword:takeout",
        "keyword:grocery", "keyword:menu", "keyword:nutrition facts",
    
        # Top-site expansion (top 3000 websites research)
        "domain:eatingwell.com",
        "domain:cooking.nytimes.com",
        "domain:food52.com",
        "domain:thepioneerwoman.com",
        "domain:yummly.com",
        "domain:marthastewart.com",
        "keyword:baking",
        "keyword:grilling",
        "keyword:slow cooker",
        "keyword:instant pot",
        "keyword:air fryer",
        "keyword:vegetarian recipe",
        "keyword:vegan recipe",
        "keyword:gluten free",
        "keyword:keto",
        "keyword:paleo",
    ],
    "Health & Medical": [
        "domain:webmd.com", "domain:mayoclinic.org", "domain:healthline.com",
        "domain:nih.gov", "domain:cdc.gov", "domain:who.int",
        "domain:drugs.com", "domain:zocdoc.com", "domain:goodrx.com",
        "domain:rxlist.com", "domain:medlineplus.gov",
        "domain:myfitnesspal.com", "domain:strava.com",
        "domain:cernerhealth.com", "domain:mychart.com",
        "domain:myhealthrecord.com", "domain:clevelandclinic.org",
        "domain:medicatechusa.com",
        # Medical imaging / PACS (user's domain)
        "domain:mavenimaging.com", "domain:support.mavenimaging.com",
        "domain:2020imaging.net",
        "domain:member.compassphs.com", "domain:compassphs.com",
        "domain:covid19criticalcare.com",
        # Additional patient portals / insurance
        "domain:anthem.com", "domain:mymoffitt.org",
        "domain:mychart.premierhealthpartners.org",
        "domain:premierhealthpartners.org",
        "domain:pullpush.io",
        # Pharmacies (online)
        "domain:modafinilxl.com", "domain:modafinilusa.com",
        "domain:alldaychemist.com", "domain:liherbals.com",
        # Tattoo / body modification
        "domain:inkdrop.co", "domain:tattoo.com",
        # General health
        "domain:medscape.com", "domain:mercola.com",
        "domain:manage.myassurantpolicy.com",
        # DICOM viewers / imaging tools
        "domain:weasis.org", "domain:osirix-viewer.com",
        "domain:radiantviewer.com", "domain:horosproject.org",
        "domain:mangosoftware.com",
        "domain:views.paperflite.com", "domain:paperflite.com",
        "keyword:dicom", "keyword:pacs", "keyword:x-ray", "keyword:radiology",
        "keyword:patient portal", "keyword:mychart", "keyword:imaging",
        "keyword:medical record", "keyword:prescription",
        "keyword:symptoms", "keyword:diagnosis", "keyword:treatment",
        "keyword:health insurance", "keyword:pharmacy",
        "keyword:fitness", "keyword:workout", "keyword:exercise",
        "keyword:mental health", "keyword:therapy", "keyword:wellness",
    
        # Top-site expansion (top 3000 websites research)
        "domain:psychologytoday.com",
        "domain:health.harvard.edu",
        "domain:nhs.uk",
        "domain:health.com",
        "domain:verywellhealth.com",
        "domain:verywellmind.com",
        "domain:verywellfit.com",
        "domain:medicalnewstoday.com",
        "domain:everydayhealth.com",
        "domain:health.gov",
        "domain:samhsa.gov",
        "domain:nimh.nih.gov",
        "domain:peloton.com",
        "domain:fitbit.com",
        "domain:noom.com",
        "domain:weightwatchers.com",
        "domain:headspace.com",
        "domain:calm.com",
        "domain:betterhelp.com",
        "domain:talkspace.com",
        "keyword:blood pressure",
        "keyword:cholesterol",
        "keyword:diabetes",
        "keyword:vaccine",
        "keyword:side effects",
        "keyword:calorie",
        "keyword:bmi",
    ],
    "Job Search & Career": [
        "domain:indeed.com", "domain:glassdoor.com", "domain:monster.com",
        "domain:ziprecruiter.com", "domain:dice.com", "domain:simplyhired.com",
        "domain:careerbuilder.com", "domain:roberthalf.com",
        "domain:upwork.com", "domain:fiverr.com", "domain:freelancer.com",
        "domain:governmentjobs.com", "domain:care.com",
        "domain:kellyservices.us", "domain:tbe.taleo.net",
        "domain:remoteok.com", "domain:levels.fyi",
        "domain:linkedin.com/jobs",
        "domain:jobs.net", "domain:careerplug.com",
        "domain:kellycareernetwork.tms.hrdepartment.com",
        "domain:tms.hrdepartment.com", "domain:hrdepartment.com",
        "domain:teamlogic-it-careers.careerplug.com",
        "domain:careers.suncoastcreditunion.com",
        "domain:workday.com", "domain:myworkday.com",
        "domain:greenhouse.io", "domain:lever.co",
        "domain:smartrecruiters.com", "domain:jobvite.com",
        "domain:bamboohr.com",
        "domain:angel.co", "domain:wellfound.com", "domain:hired.com",
        "domain:flexjobs.com", "domain:workingnomads.co",
        "domain:weworkremotely.com", "domain:remote.co",
        # Career / freelance platforms
        "domain:toptal.com", "domain:guru.com", "domain:99designs.com",
        # Subdomain patterns for company career pages
        "keyword:careers.", "keyword:jobs.",
        "keyword:job opening", "keyword:careers at", "keyword:staffing",
        "keyword:resume", "keyword:hiring", "keyword:recruiter",
        "keyword:interview", "keyword:salary",
    
        # Top-site expansion (top 3000 websites research)
        "domain:builtin.com",
        "domain:crunchbase.com",
        "domain:blind.com",
        "domain:teamblind.com",
        "domain:payscale.com",
        "domain:salary.com",
        "domain:comparably.com",
        "keyword:cover letter",
        "keyword:linkedin profile",
        "keyword:remote work",
        "keyword:work from home",
        "keyword:side hustle",
        "keyword:freelance",
    ],
    "Real Estate": [
        "domain:zillow.com", "domain:realtor.com", "domain:redfin.com",
        "domain:trulia.com", "domain:apartments.com", "domain:rent.com",
        "domain:rocketmortgage.com", "domain:appfolio.com",
        "domain:hotpads.com", "domain:compassmgmt.appfolio.com",
        "domain:forrent.com", "domain:rentcafe.com",
        "domain:auction.com", "domain:homes.com", "domain:loopnet.com",
        "domain:costar.com", "domain:landwatch.com",
        "domain:padmapper.com", "domain:streeteasy.com",
        "keyword:real estate", "keyword:for rent", "keyword:apartment",
        "keyword:condo for", "keyword:house for", "keyword:mortgage",
        "keyword:home value", "keyword:zestimate",
        "keyword:property tax", "keyword:home inspection",
        "keyword:closing cost", "keyword:hoa",
    
        # Top-site expansion (top 3000 websites research)
        "domain:movoto.com",
        "domain:coldwellbanker.com",
        "domain:century21.com",
        "domain:kw.com",
        "domain:opendoor.com",
        "domain:offerpad.com",
        "keyword:listing agent",
        "keyword:open house",
        "keyword:foreclosure",
        "keyword:commercial property",
    ],
    "Automotive": [
        # Buying / selling
        "domain:cars.com", "domain:autotrader.com", "domain:cargurus.com",
        "domain:carmax.com", "domain:kbb.com", "domain:edmunds.com",
        "domain:truecar.com", "domain:vroom.com", "domain:carvana.com",
        "domain:carfax.com", "domain:autotempest.com", "domain:autolist.com",
        # Brands
        "domain:toyota.com", "domain:ford.com", "domain:honda.com",
        "domain:chevrolet.com", "domain:bmw.com", "domain:mercedes-benz.com",
        "domain:hyundai.com", "domain:kia.com", "domain:subaru.com",
        "domain:tesla.com", "domain:rivian.com", "domain:nissan.com",
        "domain:dodge.com", "domain:jeep.com", "domain:ram.com",
        "domain:gmc.com", "domain:buick.com", "domain:cadillac.com",
        # Reviews / news
        "domain:caranddriver.com", "domain:motortrend.com", "domain:jalopnik.com",
        "domain:thedrive.com", "domain:roadandtrack.com", "domain:autoblog.com",
        "domain:carbuzz.com", "domain:torquenews.com",
        "domain:electrek.co", "domain:insideevs.com",
        # Parts / repair
        "domain:rockauto.com", "domain:autozone.com", "domain:oreillyauto.com",
        "domain:advanceautoparts.com", "domain:napaonline.com",
        "domain:repairpal.com", "domain:yourmechanic.com",
        "domain:1aauto.com", "domain:fcpeuro.com",
        # Insurance / registration
        "domain:dmv.org", "domain:geico.com/auto",
        # Keywords
        "keyword:car repair", "keyword:auto parts", "keyword:vehicle recall",
        "keyword:oil change", "keyword:car insurance", "keyword:vin check",
        "keyword:car review", "keyword:test drive", "keyword:mpg",
    
        # Top-site expansion (top 3000 websites research)
        "domain:volkswagen.com",
        "domain:audi.com",
        "domain:lexus.com",
        "domain:acura.com",
        "domain:mazda.com",
        "domain:volvo.com",
        "domain:porsche.com",
        "domain:lucidmotors.com",
        "domain:polestar.com",
        "keyword:electric vehicle",
        "keyword:ev charging",
        "keyword:car lease",
        "keyword:trade in value",
    ],
    "Sports": [
        # Major sports networks
        "domain:espn.com", "domain:sports.yahoo.com", "domain:bleacherreport.com",
        "domain:cbssports.com", "domain:foxsports.com", "domain:theathletic.com",
        "domain:sbnation.com", "domain:deadspin.com", "domain:barstoolsports.com",
        "domain:si.com", "domain:sportingnews.com", "domain:nbcsports.com",
        # Pro leagues
        "domain:nba.com", "domain:nfl.com", "domain:mlb.com", "domain:nhl.com",
        "domain:mls.com", "domain:pga.com", "domain:lpga.com",
        "domain:nascar.com", "domain:formula1.com", "domain:f1.com",
        "domain:ufc.com", "domain:sherdog.com", "domain:wwe.com",
        "domain:ncaa.com", "domain:ncaa.org",
        # Soccer / international
        "domain:goal.com", "domain:transfermarkt.com", "domain:whoscored.com",
        "domain:premierleague.com", "domain:fifa.com", "domain:uefa.com",
        "domain:flashscore.com", "domain:sofascore.com",
        # Fantasy & betting
        "domain:draftkings.com", "domain:fanduel.com", "domain:bet365.com",
        "domain:bovada.lv", "domain:betmgm.com", "domain:caesars.com",
        "domain:pointsbet.com", "domain:mybookie.ag",
        # Stats & reference
        "domain:pro-football-reference.com", "domain:basketball-reference.com",
        "domain:baseball-reference.com", "domain:hockey-reference.com",
        "domain:statmuse.com", "domain:covers.com",
        # Fitness / running
        "domain:runnersworld.com", "domain:bicycling.com",
        "domain:swimswam.com", "domain:letsrun.com",
        "keyword:sports scores", "keyword:game recap", "keyword:standings",
        "keyword:fantasy football", "keyword:fantasy basketball",
        "keyword:sportsbook", "keyword:point spread",
    
        # Top-site expansion (top 3000 websites research)
        "domain:laliga.com",
        "domain:bundesliga.com",
        "domain:seriea.com",
        "domain:livescore.com",
        "domain:cricbuzz.com",
        "domain:espncricinfo.com",
        "domain:icc-cricket.com",
        "domain:olympic.org",
        "domain:olympics.com",
        "domain:motogp.com",
        "domain:indycar.com",
        "domain:boxrec.com",
        "domain:tapology.com",
        "domain:247sports.com",
        "domain:rivals.com",
        "domain:atptour.com",
        "domain:wtatennis.com",
        "domain:pgatour.com",
        "keyword:world cup",
        "keyword:championship",
        "keyword:playoffs",
        "keyword:draft pick",
        "keyword:match result",
        "keyword:score update",
    ],
    "Government & Legal": [
        "regex:\\.gov(/|$)", "domain:usa.gov", "domain:irs.gov", "domain:ssa.gov",
        "domain:cms.gov", "domain:sec.gov", "domain:fda.gov",
        "domain:fcc.gov", "domain:ftc.gov",
        "domain:law.cornell.edu", "domain:findlaw.com",
        "domain:sunbiz.org", "domain:search.sunbiz.org",
        "domain:myflorida.com", "domain:flhsmv.gov", "domain:floridajobs.org",
        "domain:mydmvportal-flhsmv.my.site.com",
        # Additional legal/court
        "domain:pacer.gov", "domain:uscourts.gov",
        "domain:justia.com", "domain:nolo.com", "domain:rocketlawyer.com",
        "domain:legalzoom.com", "domain:avvo.com",
        # International
        "domain:gov.uk", "domain:canada.ca", "domain:gov.au",
        # State / local government
        "domain:state.fl.us", "domain:state.oh.us",
        "domain:myfloridalicense.com", "domain:ohio.gov",
        "keyword:government", "keyword:federal", "keyword:legislation",
        "keyword:court case", "keyword:public record", "keyword:tax filing",
        "keyword:social security", "keyword:voter registration",
    
        # Top-site expansion (top 3000 websites research)
        "domain:whitehouse.gov",
        "domain:congress.gov",
        "domain:senate.gov",
        "domain:house.gov",
        "domain:nasa.gov",
        "domain:fbi.gov",
        "domain:cia.gov",
        "domain:dhs.gov",
        "domain:census.gov",
        "domain:epa.gov",
        "domain:faa.gov",
        "domain:osha.gov",
        "domain:treasury.gov",
        "domain:state.gov",
        "domain:ed.gov",
        "domain:hhs.gov",
        "domain:va.gov",
        "domain:un.org",
        "domain:europa.eu",
        "domain:ec.europa.eu",
        "domain:unesco.org",
        "domain:worldbank.org",
        "domain:imf.org",
        "keyword:executive order",
        "keyword:bill passed",
        "keyword:supreme court",
        "keyword:amendment",
    ],
    "Downloads & Torrents": [
        "domain:1337x.to", "domain:thepiratebay.org", "domain:rarbg.to",
        "domain:nyaa.si", "domain:fitgirl-repacks.site",
        "domain:thehouseofportable.com", "domain:filecr.com",
        "domain:rutracker.org", "domain:thegeeks.bz", "domain:torrentgalaxy.to",
        "domain:yts.mx", "domain:eztv.re", "domain:limetorrents.info",
        "domain:forum.mobilism.me", "domain:mobilism.me",
        "domain:mega.nz", "domain:mediafire.com", "domain:file-upload.org",
        "domain:fcportables.com",
        # Piracy indexes / releases
        "domain:fmhy.net", "domain:lookmovie2.to", "domain:kickass.to",
        "domain:palined.com", "domain:filepursuit.com", "domain:usersdrive.com",
        "domain:predb.net", "domain:redact.dev",
        "domain:w16.monkrus.ws", "domain:monkrus.ws",
        "domain:couchtuner.show", "domain:shrimpstreams.live",
        "domain:cnvmp3.com",
        # File hosts
        "domain:filenext.com", "domain:katfile.com", "domain:rapidgator.net",
        "domain:uploadgig.com", "domain:nitroflare.com", "domain:keep2share.cc",
        # DDL archives
        "domain:softarchive.is", "domain:downloadly.ir",
        "domain:getintopc.com", "domain:igg-games.com",
        "domain:ocean-of-games.com", "domain:oceanofgames.com",
        "domain:skidrowreloaded.com", "domain:skidrow-games.com",
        "keyword:torrent", "keyword:magnet", "keyword:seedbox",
        "keyword:nulled", "keyword:crack", "keyword:warez",
        "keyword:free download", "keyword:direct download",
        "keyword:scene release",
    
        # Top-site expansion (top 3000 websites research)
        "domain:apkpure.com",
        "domain:apkmirror.com",
        "domain:fosshub.com",
        "keyword:iso download",
        "keyword:portable download",
        "keyword:offline installer",
    ],
    "Media Production & Design": [
        # Video Equipment
        "domain:teradek.com", "domain:blackmagicdesign.com",
        "domain:obsproject.com", "domain:sbe.org",
        # Graphics & Templates
        "domain:gfxtra.com", "domain:gfxdrug.com", "domain:gfxdownload.com",
        "domain:intro-hd.net", "domain:freepreset.net", "domain:freevideoeffect.com",
        "domain:motionarray.com", "domain:envato.com", "domain:elements.envato.com",
        "domain:prodesigntools.com", "domain:helpx.adobe.com", "domain:adobe.com",
        "domain:creativecloud.adobe.com",
        # Stock Media
        "domain:pexels.com", "domain:unsplash.com", "domain:pixabay.com",
        "domain:shutterstock.com", "domain:gettyimages.com",
        "domain:videvo.net", "domain:artlist.io",
        # Design Tools
        "domain:dribbble.com", "domain:behance.net", "domain:99designs.com",
        "domain:brandcrowd.com", "domain:looka.com",
        "domain:freepik.com", "domain:flaticon.com", "domain:iconmonstr.com",
        "domain:icons8.com", "domain:fontawesome.com",
        "domain:dafont.com", "domain:fontsquirrel.com",
        "domain:pngwing.com", "domain:canva.com", "domain:figma.com",
        # GFX / VFX repositories
        "domain:gfxtra31.com",
        "domain:vfxdownload.net", "domain:psdflyer.co", "domain:nitrogfx.pro",
        "domain:free-psd-templates.com", "domain:scriptmafia.org",
        "domain:graphicriver.net", "domain:videohive.net",
        "domain:templatemonster.com", "domain:themeforest.net",
        "domain:awesomeflyer.com", "domain:ae-share.com", "domain:ae-project.su",
        # UI / animation tools
        "domain:loading.io", "domain:lottiefiles.com",
        "domain:keyshape.app", "domain:vectr.com",
        # Audio / video editing
        "domain:audiojungle.net", "domain:soundsnap.com",
        "domain:producerspot.com",
        "keyword:after effects", "keyword:premiere pro", "keyword:stock footage",
        "keyword:videohive", "keyword:motion graphic",
        "keyword:psd template", "keyword:photoshop template",
        "keyword:vfx", "keyword:cinema 4d", "keyword:blender",
    
        # Top-site expansion (top 3000 websites research)
        "domain:sketch.com",
        "domain:invisionapp.com",
        "domain:whimsical.com",
        "domain:creativemarket.com",
        "domain:istockphoto.com",
        "domain:smugmug.com",
        "domain:remove.bg",
        "domain:typewolf.com",
        "keyword:logo design",
        "keyword:brand identity",
        "keyword:color palette",
        "keyword:wireframe",
        "keyword:mockup",
        "keyword:prototype",
    ],
    "Software & Customization": [
        # Windows Themes
        "domain:vsthemes.org", "domain:deviantart.com", "domain:windhawk.net",
        "domain:startallback.com", "domain:stardock.com", "domain:rainmeter.net",
        "keyword:theme", "keyword:wallpaper", "keyword:dark mode",
        # Applications
        "domain:ninite.com", "domain:portableapps.com", "domain:portablefreeware.com",
        "domain:majorgeeks.com", "domain:softpedia.com", "domain:filehippo.com",
        "domain:alternativeto.net", "domain:wingetgui.com",
        "domain:voidtools.com", "domain:freewaregenius.com",
        "domain:mozilla.org", "domain:mozilla.com",
        "domain:7-zip.org", "domain:notepad-plus-plus.org",
        "domain:videolan.org", "domain:handbrake.fr", "domain:audacity.org",
        "domain:gimp.org", "domain:inkscape.org", "domain:libreoffice.org",
        # More popular apps
        "domain:obsidian.md", "domain:logseq.com", "domain:anytype.io",
        "domain:zotero.org", "domain:calibre-ebook.com",
        "domain:keepass.info", "domain:keepassxc.org",
        "domain:veracrypt.fr", "domain:truecrypt.ch",
        "domain:everything.voidtools.com",
        "domain:fastcopy.jp", "domain:teracopy.com",
    ],
    "Productivity & Tools": [
        # Google Workspace
        "domain:docs.google.com", "domain:drive.google.com",
        "domain:sheets.google.com", "domain:slides.google.com",
        "domain:keep.google.com", "domain:calendar.google.com",
        "domain:sites.google.com", "domain:photos.google.com",
        "domain:fonts.google.com",
        # Email & Communication
        "domain:mail.google.com", "domain:outlook.live.com",
        "domain:outlook.office.com", "domain:login.live.com",
        "domain:mail.yahoo.com", "domain:messages.google.com",
        "domain:aol.com", "domain:mail.com", "domain:fastmail.com",
        "domain:tuta.io", "domain:tutanota.com",
        # Online Tools
        "domain:notion.so", "domain:trello.com", "domain:asana.com",
        "domain:airtable.com", "domain:feedly.com",
        "domain:iloveimg.com", "domain:ilovepdf.com", "domain:ezgif.com",
        "domain:cloudconvert.com",
        "domain:hubspot.com",
        # Cloud storage (user-facing productivity)
        "domain:dropbox.com", "domain:onedrive.live.com", "domain:onedrive.com",
        "domain:box.com", "domain:sync.com", "domain:pcloud.com",
        # Other productivity
        "domain:tunemymusic.com",  # music playlist tool
        "domain:toggl.com", "domain:harvestapp.com",
        "domain:clockify.me", "domain:rescuetime.com",
        "domain:evernote.com", "domain:onenote.com",
        "domain:monday.com", "domain:clickup.com", "domain:basecamp.com",
        "domain:miro.com", "domain:mural.co", "domain:lucidchart.com",
        "domain:draw.io", "domain:app.diagrams.net",
        # Calendar / scheduling
        "domain:calendly.com", "domain:doodle.com",
        # Password managers (primary utility for many)
        "domain:1password.com", "domain:dashlane.com",
        # Google.com catch-all (last fallback for generic searches/accounts).
        # Keep at the very end so specific subdomain rules in other
        # categories (News, AI, Cloud, Reference) match first.
        "domain:google.com",
    
        # Top-site expansion (top 3000 websites research)
        "domain:zapier.com",
        "domain:ifttt.com",
        "domain:typeform.com",
        "domain:jotform.com",
        "domain:xero.com",
        "domain:grammarly.com",
        "domain:deepl.com",
        "domain:hootsuite.com",
        "domain:later.com",
        "keyword:task manager",
        "keyword:project management",
        "keyword:time tracking",
        "keyword:invoice",
        "keyword:crm",
        "keyword:email marketing",
        "keyword:form builder",
        "keyword:automation",
    ],
}

