"""Default categorization patterns - 1,583 patterns across 32 categories.

Built from real-world bookmark analysis of 5,000+ bookmarks. Covers 800+ popular
domains. Achieves 84.3% auto-categorization coverage on real bookmark exports.
Pattern types supported: plain, domain:, keyword:, regex:, path:, title:.
"""

DEFAULT_CATEGORIES = {
    "Uncategorized / Needs Review": [
        "example.com", "example.org", "test.", "demo.", "staging."
    ],
    "Adult & Mature Content": [
        "pornhub.com", "xvideos.com", "xnxx.com", "xhamster.com", "redtube.com",
        "porn.", "xxx.", "chaturbate.com", "onlyfans.com", "fansly.com",
        "youporn.com", "tube8.com", "spankbang.com", "eporner.com",
        "motherless.com", "youjizz.com", "fuq.com", "nudevista.com",
        "domain:tabootube.xxx", "domain:filtradas.com",
        "domain:16ebalka.ru.actor", "domain:av4us.online",
        "domain:ins-dream.com",
        "keyword:porn", "keyword:xxx", "keyword:nsfw", "keyword:erotic",
        "keyword:incest", "keyword:onlyfans", "keyword:adult video",
    ],
    "Redirects, Trackers & Shorteners": [
        "domain:bit.ly", "domain:bitly.com", "domain:tinyurl.com",
        "domain:t.co", "domain:goo.gl", "domain:ow.ly",
        "domain:linktr.ee", "domain:linkin.bio",
        "domain:rebrand.ly", "domain:cutt.ly", "domain:is.gd",
        "domain:v.gd", "domain:shorturl.at",
        "domain:linkvertise.com", "domain:adf.ly", "domain:ouo.io",
        "redirect.", "tracking.", "click.",
        "utm_source=", "fbclid=", "gclid=", "mc_eid="
    ],
    "Internal Tools & Dashboards": [
        "localhost", "127.0.0.1", "192.168.", "10.0.", "172.16.", ".local",
        ".internal", ".lan", ":3000", ":8080", ":8443", ":9090", ":5000",
        "/admin", "/dashboard", "admin.", "dashboard.", "internal.", "intranet.",
        "domain:pfsense", "domain:opnsense", "domain:unifi"
    ],
    "Privacy & Security": [
        "domain:1password.com", "domain:lastpass.com", "domain:bitwarden.com",
        "domain:protonmail.com", "domain:proton.me", "domain:nordvpn.com",
        "domain:expressvpn.com", "domain:mullvad.net", "domain:torproject.org",
        "domain:signal.org", "domain:haveibeenpwned.com", "domain:privacyguides.org",
        "domain:privacytools.io", "domain:virustotal.com", "domain:keepassxc.org",
        "domain:tails.boum.org", "domain:whonix.org",
        "keyword:vpn", "keyword:privacy", "keyword:encrypt"
    ],
    "Self-Hosted & Homelab": [
        "domain:pfsense.org", "domain:opnsense.org", "domain:proxmox.com",
        "domain:truenas.com", "domain:unraid.net", "domain:synology.com",
        "domain:home-assistant.io", "domain:jellyfin.org", "domain:plex.tv",
        "domain:sonarr.tv", "domain:radarr.video", "domain:nextcloud.com",
        "domain:pi-hole.net", "domain:portainer.io", "domain:emby.media",
        "domain:cockpit-project.org", "domain:homer-dashboard.com",
        "domain:wireguard.com", "domain:tailscale.com", "domain:zerotier.com"
    ],
    "SysAdmin & IT": [
        # Windows & Group Policy
        "domain:getadmx.com", "domain:admx.help", "domain:schneegans.de",
        "domain:winaero.com", "keyword:group policy", "keyword:gpedit",
        "keyword:admx", "keyword:unattend", "keyword:windows 10", "keyword:windows 11",
        "keyword:windows server", "keyword:powershell", "keyword:registry",
        "keyword:sccm", "keyword:intune", "keyword:wsus",
        "domain:go.microsoft.com", "domain:learn.microsoft.com",
        "domain:docs.microsoft.com", "domain:devblogs.microsoft.com",
        # Networking & DNS
        "domain:dnscheck.tools", "domain:mxtoolbox.com", "domain:whatismyip.com",
        "domain:dnschecker.org", "domain:dnsviz.net", "domain:ipchicken.com",
        "domain:whatsmydns.net", "domain:who.is", "domain:whois.com",
        "domain:speedtest.net", "domain:speakeasy.net", "domain:wifiman.com",
        "keyword:speed test", "keyword:dns", "keyword:whois",
        # Hardware & Drivers
        "domain:dell.com", "domain:hp.com", "domain:lenovo.com",
        "domain:intel.com", "domain:amd.com", "domain:nvidia.com",
        "domain:toshiba.com", "domain:gsmarena.com", "domain:amcrest.com",
        "domain:tomshardware.com", "domain:anandtech.com", "domain:pcpartpicker.com",
        # IT Forums & Resources
        "domain:tenforums.com", "domain:elevenforum.com", "domain:serverfault.com",
        "domain:spiceworks.com", "domain:ghacks.net", "domain:askwoody.com",
        "domain:howtogeek.com", "domain:techrepublic.com",
        "domain:windowscentral.com", "domain:neowin.net", "domain:theregister.com",
        "domain:computerworld.com", "domain:bleepingcomputer.com",
        # Remote Access & Management
        "domain:splashtop.com", "domain:screenconnect.com", "domain:connectwise.com",
        "domain:ninjaone.com", "domain:pdq.com", "domain:teamviewer.com",
        "domain:anydesk.com", "domain:remotedesktop.google.com",
        "domain:sync.com", "domain:info.easyvista.com", "domain:easyvista.com",
        "domain:teamlogicit.com", "domain:tech-keys.com",
        "domain:nexttechconsultants.com",
        # Status pages
        "domain:cloudflarestatus.com", "domain:status.microsoft", "domain:azure.status.microsoft",
        "domain:status.github.com", "domain:status.digitalocean.com",
        "domain:githubstatus.com", "domain:downdetector.com",
        # Microsoft ecosystem
        "domain:login.microsoftonline.com", "domain:microsoftonline.com",
        "domain:answers.microsoft.com", "domain:support.microsoft.com",
        "domain:technet.microsoft.com", "domain:developer.microsoft.com",
        "domain:security.microsoft.com", "domain:apps.microsoft.com",
        "domain:microsoft.com",
        # Image tools (sysadmin uses for processing)
        "domain:imagemagick.org", "domain:joesandbox.com",
        "domain:any.run", "domain:urlscan.io",
        # Customization tools
        "domain:wincustomize.com",
        # Networking / enterprise vendors
        "domain:cisco.com", "domain:juniper.net", "domain:arubanetworks.com",
        "domain:ubnt.com", "domain:ubiquiti.com", "domain:mikrotik.com",
        "domain:fortinet.com", "domain:sonicwall.com", "domain:sophos.com",
        "domain:meraki.com",
        "domain:netadmintools.com", "domain:carbonite.com",
        "domain:osticket.com", "domain:palmtreeit.org",
        "domain:myersinfosys.com", "domain:sysadminpedia.com",
        # Home networking
        "domain:myhomenetwork.att.com", "domain:att.com", "domain:xfinity.com",
        "domain:spectrum.com", "domain:comcast.com", "domain:cox.com",
        # SysAdmin tools (Windows)
        "domain:nirsoft.net", "domain:ntlite.com",
        "domain:autoitscript.com", "domain:autohotkey.com",
        "domain:winutil.christitus.com", "domain:christitus.com",
        "domain:marticliment.com",  # UniGetUI
        "domain:uninstalr.com", "domain:pete.akeo.ie",  # Rufus
        "domain:abelhadigital.com",  # HostsMan
        "domain:custopack.com", "domain:librewolf.net",
        "domain:spicetify.app",
        "domain:process-hacker.com", "domain:processhacker.sourceforge.io",
        "domain:sysinternals.com", "domain:live.sysinternals.com",
        # Meeting / remote support
        "domain:zoom.us", "domain:zoomgov.com", "domain:webex.com",
        "domain:gotomeeting.com", "domain:bluejeans.com",
        "domain:logmein.com", "domain:gotoassist.com",
        "domain:dualmon.com",
        # IT training / cheat sheets
        "domain:gfi.com", "domain:sysadmincasts.com", "domain:gestaltit.com",
        "domain:9tut.com", "domain:examcollection.com", "domain:avanset.com",
        # IT forums / utilities
        "domain:forum.avast.com", "domain:avast.com",
        "domain:icoconverter.com", "domain:mdl-tb.ct8.pl",
        # Enterprise software
        "domain:avid.force.com", "domain:ricoh-usa.com", "domain:ricoh.com",
        "domain:xerox.com", "domain:canon.com", "domain:brother.com",
        # Accounts / auth
        "domain:accounts.bdrive.com", "domain:bdrive.com",
        # File sharing / storage / backup (sysadmin context)
        "domain:wetransfer.com", "domain:sendspace.com",
        "domain:box.net", "domain:box.com", "domain:wuala.com",
        "domain:ammyy.com", "domain:airdroid.com", "domain:web.airdroid.com",
        "domain:dragshare.com", "domain:whatbox.ca", "domain:whatbox.com",
        "domain:hetzner.com", "domain:hetzner.online",
        "domain:ovhcloud.com", "domain:ovh.com",
        "domain:vultr.com", "domain:linode.com",
        # pfSense / security hardware
        "domain:netgate.com", "domain:pfsense.com",
        # Printer / hardware vendors
        "domain:global-print-driver.com", "domain:xerox.com",
        "domain:hp.com", "domain:epson.com", "domain:brother.com",
        # Other SysAdmin resources / utilities
        "domain:ez.lol",  # browser ID/extension tester
        "keyword:managed it", "keyword:it services", "keyword:it support",
        "keyword:endpoint", "keyword:patch management", "keyword:rmm",
        "keyword:active directory", "keyword:ldap", "keyword:dhcp",
        "keyword:firewall", "keyword:vlan", "keyword:subnet",
        "keyword:bitlocker", "keyword:tpm", "keyword:uefi", "keyword:bios",
        "keyword:virtualbox", "keyword:hyper-v", "keyword:vmware",
        "keyword:remote desktop", "keyword:remote admin", "keyword:remote control",
        "keyword:web hosting", "keyword:vps", "keyword:dedicated server",
        "keyword:backup solution", "keyword:file sharing",
        "keyword:cloud storage", "keyword:data backup",
        "keyword:virtual machine", "keyword:vm image",
        "keyword:pfsense", "keyword:opnsense", "keyword:netgate",
        "keyword:print driver", "keyword:printer setup",
    ],
    "Development & Programming": [
        # Code Hosting
        "domain:github.com", "domain:gitlab.com", "domain:bitbucket.org",
        "domain:codeberg.org", "domain:sourceforge.net",
        "domain:gist.github.com", "domain:raw.githubusercontent.com",
        # Q&A & Community
        "domain:stackoverflow.com", "domain:stackexchange.com",
        "domain:superuser.com", "domain:serverfault.com", "domain:dev.to",
        # IDEs & Playgrounds
        "domain:codepen.io", "domain:jsfiddle.net", "domain:replit.com",
        "domain:codesandbox.io", "domain:stackblitz.com",
        # Package Managers
        "domain:npmjs.com", "domain:pypi.org", "domain:crates.io",
        "domain:packagist.org", "domain:rubygems.org", "domain:nuget.org",
        # Competitive
        "domain:hackerrank.com", "domain:leetcode.com", "domain:codeforces.com",
        # Documentation
        "domain:developer.mozilla.org", "domain:w3schools.com",
        "domain:css-tricks.com", "domain:smashingmagazine.com",
        # Userscripts & Extensions
        "domain:greasyfork.org", "domain:openuserjs.org",
        "domain:userstyles.world", "domain:userstyles.org", "domain:userscripts.org",
        "domain:chromewebstore.google.com", "domain:addons.mozilla.org",
        "domain:uso.kkx.one",
        # Web Development
        "domain:themeforest.net", "domain:tailwindcss.com",
        "domain:vercel.com", "domain:netlify.com", "domain:heroku.com",
        # Dev Tools
        "domain:regex101.com", "domain:jsonformatter.org",
        "domain:producthunt.com", "domain:pastebin.com",
        "domain:community.chocolatey.org", "domain:chocolatey.org",
        "domain:winget.run", "domain:xda-developers.com",
        "domain:play.google.com",
        "domain:chrome.google.com",  # Chrome Web Store (old URL)
        # User's own / tools
        "domain:sysadmindoc.github.io",
        "domain:discuss.ipfs.tech", "domain:ipfs.io", "domain:ipfs.tech",
        "domain:someonewhocares.org",
        "domain:scrapy.org", "domain:remotion.dev",
        "domain:github.developerdan.com",
        "domain:tools.thatwind.com",
        "domain:chrome-stats.com", "domain:crxextractor.com",
        "domain:allpurposedesigns.com",
        "domain:a.dove.isdumb.one",
        "domain:massgrave.dev",
        "domain:console.firebase.google.com", "domain:firebase.google.com",
        # More IDEs / playgrounds
        "domain:glitch.com", "domain:observablehq.com", "domain:runkit.com",
        "domain:pythonanywhere.com", "domain:colab.google",
        # More docs
        "domain:readthedocs.io", "domain:readthedocs.org",
        "domain:godoc.org", "domain:pkg.go.dev",
        # API testing
        "domain:postman.com", "domain:insomnia.rest", "domain:httpbin.org",
        # Additional dev platforms / services
        "domain:supabase.com", "domain:expo.dev", "domain:go.dev",
        "domain:reactbits.dev", "domain:hlsjs.video-dev.org", "domain:video-dev.org",
        "domain:developertoolkits.com",
        # Online tools (dev-oriented)
        "domain:zamzar.com", "domain:textcleaner.net",
        "domain:base64-image.de", "domain:base64.guru",
        "domain:jsonlint.com", "domain:jsonformatter.curiousconcept.com",
        "domain:crontab.guru", "domain:explainshell.com",
        "domain:caniuse.com", "domain:devdocs.io", "domain:devhints.io",
        "domain:tldr.sh", "domain:tldr.inbrowser.app",
        # Dev blogs / personal dev sites
        "domain:vikash.nl", "domain:helloacm.com",
        "domain:blog.bahraniapps.com", "domain:bahraniapps.com",
        "domain:proggblo.blogspot.com",
        # Sysadmin scripting / extensions
        "domain:pro.sorrywatermark.com",
        # Game server / bot hosting
        "domain:dyno.gg",
        "keyword:userscript", "keyword:tampermonkey", "keyword:greasemonkey",
        "keyword:api documentation", "keyword:sdk", "keyword:github repo",
        "keyword:pull request", "keyword:pry request",
    ],
    "AI & Machine Learning": [
        # AI Assistants
        "domain:openai.com", "domain:anthropic.com", "domain:claude.ai",
        "domain:status.claude.com", "domain:chatgpt.com", "domain:chat.openai.com",
        "domain:gemini.google.com", "domain:aistudio.google.com", "domain:labs.google",
        "domain:poe.com", "domain:perplexity.ai", "domain:deepseek.com",
        "domain:chat.deepseek.com", "domain:copilot.microsoft.com",
        "domain:pi.ai", "domain:character.ai", "domain:chub.ai",
        "domain:chat.qwen.ai",
        # AI Development
        "domain:huggingface.co", "domain:kaggle.com",
        "domain:tensorflow.org", "domain:pytorch.org",
        "domain:colab.research.google.com", "domain:replicate.com",
        "domain:ollama.com", "domain:lmstudio.ai", "domain:cursor.com",
        "domain:cursor.sh", "domain:codeium.com", "domain:together.ai",
        "domain:groq.com", "domain:cohere.com", "domain:mistral.ai",
        "domain:ai.google.dev", "domain:console.anthropic.com",
        "domain:docs.anthropic.com", "domain:n8n.io",
        # AI Art & Media
        "domain:midjourney.com", "domain:stability.ai", "domain:civitai.com",
        "domain:suno.com", "domain:suno.ai", "domain:udio.com",
        "domain:elevenlabs.io", "domain:runwayml.com", "domain:kaiber.ai",
        "domain:leonardo.ai", "domain:ideogram.ai", "domain:pika.art",
        "domain:luma.ai", "domain:dreamstudio.ai", "domain:clipdrop.co",
        "domain:nightcafe.studio", "domain:heygen.com", "domain:murf.ai",
        "domain:hailuoai.video", "domain:napkin.ai",
        "domain:grok.com", "domain:grok.x.ai", "domain:x.ai",
        "domain:notebooklm.google.com", "domain:openrouter.ai",
        "domain:ink.trimythic.co", "domain:tattoosai.com",
        "domain:app.klingai.com", "domain:klingai.com",
        "domain:hailuo-02.com", "domain:minimax.io",
        "domain:stoat.chat", "domain:geminivideo.studio",
        "domain:prompts.chat", "domain:bitlife.ai",
        "domain:otter.ai", "domain:lenso.ai", "domain:copyseeker.net",
        "domain:apollo.io", "domain:jeneratex.com",
        "domain:app.patientimage.ai", "domain:app.vivalabs.ai",
        "domain:jobo.world", "domain:app.bio.link",
        "domain:tunemymusic.com", "domain:photopea.com",
        "domain:gab.ai", "domain:freedom-gpt.com",
        "domain:venice.ai", "domain:agnai.chat",
        "domain:you.com", "domain:phind.com",
        "domain:tldraw.com", "domain:cody.ai",
        "domain:tabnine.com", "domain:continue.dev",
        "keyword:ai model", "keyword:llm", "keyword:large language",
        "keyword:machine learning", "keyword:deep learning",
        "keyword:ai generator", "keyword:ai video", "keyword:ai image",
        "keyword:ai tool", "keyword:ai chatbot", "keyword:ai assistant",
        "keyword:prompt engineering", "keyword:fine-tuning",
    ],
    "Cloud & Infrastructure": [
        "domain:aws.amazon.com", "domain:console.aws.amazon.com",
        "domain:azure.microsoft.com", "domain:portal.azure.com",
        "domain:cloud.google.com", "domain:digitalocean.com",
        "domain:linode.com", "domain:vultr.com", "domain:hetzner.com",
        "domain:cloudflare.com", "domain:dash.cloudflare.com",
        "domain:namecheap.com", "domain:godaddy.com", "domain:domains.google.com",
        "domain:squarespace.com", "domain:wordpress.com", "domain:wordpress.org",
        "domain:cpanel.com", "domain:one.com", "domain:siteground.com",
        "domain:hostinger.com", "domain:bluehost.com", "domain:dreamhost.com",
        "keyword:docker", "keyword:kubernetes", "keyword:terraform",
        "keyword:ansible", "keyword:vmware", "keyword:esxi", "keyword:proxmox"
    ],
    "News & Media": [
        "domain:cnn.com", "domain:bbc.com", "domain:bbc.co.uk",
        "domain:reuters.com", "domain:apnews.com", "domain:nytimes.com",
        "domain:washingtonpost.com", "domain:theguardian.com",
        "domain:bloomberg.com", "domain:techcrunch.com",
        "domain:foxnews.com", "domain:nbcnews.com", "domain:cbsnews.com",
        "domain:abcnews.go.com", "domain:npr.org", "domain:usatoday.com",
        "domain:latimes.com", "domain:nypost.com", "domain:msn.com",
        "domain:news.google.com", "domain:news.ycombinator.com",
        "domain:breitbart.com", "domain:dailymail.co.uk", "domain:zerohedge.com",
        "domain:infowars.com", "domain:newsmax.com", "domain:theblaze.com",
        "domain:drudgereport.com", "domain:revolver.news",
        "domain:thegatewaypundit.com", "domain:americanthinker.com",
        "domain:theverge.com", "domain:wired.com", "domain:engadget.com",
        "domain:vice.com", "domain:vox.com", "domain:slate.com",
        "domain:salon.com", "domain:huffpost.com", "domain:politico.com",
        "domain:thehill.com", "domain:axios.com", "domain:mashable.com",
        "domain:thedailybeast.com", "domain:medium.com", "domain:substack.com",
        "domain:libertylinks.io",
        # Local news / regional
        "domain:whio.com", "domain:whiotv.com",
        "domain:thinktv.org", "domain:downtowndayton.org",
        # Alternative / political
        "domain:infogalactic.com", "domain:bellingcat.gitbook.io", "domain:bellingcat.com",
        "domain:dailywire.com", "domain:mises.org",
        "domain:frontier.com", "domain:theepochtimes.com", "domain:theconservativetreehouse.com",
        "domain:zerohedge.com", "domain:citizenfreepress.com",
        # Science / education news
        "domain:nuclearsecrecy.com", "domain:sciencedaily.com",
        "domain:phys.org", "domain:space.com",
        "domain:arstechnica.com", "domain:hackernoon.com",
        # General interest / lifestyle
        "domain:lifehacker.com", "domain:buzzfeed.com",
        "domain:ted.com", "domain:goodreads.com",
        "domain:atlasobscura.com", "domain:bigthink.com",
        "domain:aeon.co", "domain:nautil.us",
        # Personal blogs / authors (common unknown)
        "domain:todaywillbedifferent.com",
        "domain:brittanyanneauthor.com",
    ],
    "Weather & Meteorology": [
        "domain:weather.com", "domain:weather.gov", "domain:noaa.gov",
        "domain:nhc.noaa.gov", "domain:star.nesdis.noaa.gov",
        "domain:tropicaltidbits.com", "domain:wunderground.com",
        "domain:accuweather.com", "domain:windy.com", "domain:ventusky.com",
        "domain:earth.nullschool.net", "domain:zoom.earth",
        "domain:lightningmaps.org", "domain:spaghettimodels.com",
        "domain:rammb-slider.cira.colostate.edu", "domain:cira.colostate.edu",
        "domain:web.weatherwise.app", "domain:weatherwise.app",
        "domain:staticbaronwebapps.velocityweather.com", "domain:velocityweather.com",
        "domain:s.w-x.co", "domain:w-x.co",
        "domain:pivotalweather.com", "domain:mrx.com",
        "domain:stormtrack.org", "domain:aviationweather.gov",
        "keyword:weather", "keyword:forecast", "keyword:hurricane",
        "keyword:tropical storm", "keyword:tornado", "keyword:radar",
        "keyword:doppler", "keyword:severe weather",
    ],
    "Social Media": [
        "domain:twitter.com", "domain:x.com", "domain:nitter.net",
        "domain:facebook.com", "domain:m.facebook.com", "domain:fb.com",
        "domain:instagram.com", "domain:linkedin.com",
        "domain:tiktok.com", "domain:pinterest.com", "domain:tumblr.com",
        "domain:snapchat.com", "domain:threads.net",
        "domain:bluesky.app", "domain:bsky.app",
        "domain:mastodon.social", "domain:nextdoor.com"
    ],
    "Forums & Communities": [
        "domain:reddit.com", "domain:old.reddit.com", "domain:new.reddit.com",
        "domain:quora.com", "domain:discord.com", "domain:discord.gg",
        "domain:slack.com", "domain:telegram.org", "domain:t.me",
        "domain:boards.4chan.org", "domain:boards.4channel.org",
        "domain:4chan.org", "domain:4channel.org",
        "domain:godlikeproductions.com",
        "domain:forums.somethingawful.com", "domain:somethingawful.com",
        "domain:kiwifarms.net", "domain:imgur.com",
        "domain:voat.co", "domain:scored.co", "domain:communities.win",
        "domain:gab.com", "domain:truthsocial.com", "domain:minds.com",
        "domain:parler.com", "domain:gettr.com", "domain:ruqqus.com",
        "domain:8ch.net", "domain:8kun.top",
        "domain:patriots.win", "domain:communities.win",
        "domain:kiwifarms.st", "domain:kiwifarms.net",
        "domain:16chan.xyz", "domain:16chan.to",
        "domain:ar15.com", "domain:thehighroad.org",
        "domain:forum.aprelteam.su", "domain:aprelteam.su",
        # Additional forum / community platforms
        "domain:twitch.tv/directory", "domain:vk.com",
        "domain:tapatalk.com", "domain:proboards.com",
        "domain:forums.redflagdeals.com", "domain:slickdeals.net",
        "keyword:discussion forum", "keyword:subreddit",
    ],
    "Shopping & E-commerce": [
        "domain:amazon.com", "domain:smile.amazon.com", "domain:camelcamelcamel.com",
        "domain:ebay.com", "domain:walmart.com", "domain:target.com",
        "domain:bestbuy.com", "domain:etsy.com", "domain:aliexpress.com",
        "domain:shopify.com", "domain:newegg.com", "domain:bhphotovideo.com",
        "domain:wish.com", "domain:temu.com", "domain:shein.com",
        "domain:wayfair.com", "domain:homedepot.com", "domain:lowes.com",
        "domain:costco.com", "domain:samsclub.com", "domain:ikea.com",
        "domain:overstock.com", "domain:menards.com", "domain:harborfreight.com",
        "domain:monoprice.com", "domain:kohls.com", "domain:macys.com",
        "domain:nordstrom.com", "domain:zappos.com",
        "domain:craigslist.org", "domain:offerup.com", "domain:mercari.com",
        "domain:poshmark.com", "domain:swappa.com",
        "domain:fedex.com", "domain:ups.com", "domain:usps.com",
        "domain:cvs.com", "domain:walgreens.com",
        # Firearms & Outdoor
        "domain:gunbroker.com", "domain:guns.com", "domain:impactguns.com",
        "domain:palmettostatearmory.com", "domain:budsgunshop.com",
        "domain:classicfirearms.com", "domain:ammoseek.com",
        "domain:midwayusa.com", "domain:brownells.com",
        "domain:cheaperthandirt.com", "domain:sportsmansguide.com",
        "domain:truegunvalue.com", "domain:springfield-armory.com",
        "domain:rei.com", "domain:bassproshops.com", "domain:cabelas.com",
        "domain:dickssportinggoods.com",
        # Outdoor / clothing
        "domain:kuhl.com", "domain:patagonia.com", "domain:northface.com",
        "domain:columbia.com",
        # Home furnishings
        "domain:thefurniturewarehouse.com", "domain:firebox.com",
        "domain:beautyrest.com", "domain:secretlab.co",
        # Storage
        "domain:myaccount.extraspace.com", "domain:extraspace.com",
        "domain:publicstorage.com", "domain:cubesmart.com",
        # Misc specialty
        "domain:laserpointerpro.com", "domain:woodhullusa.com",
        "domain:northerner.com", "domain:drizly.com",
        "domain:zero.com",
        # Tobacco / vape
        "domain:gotsmoke.com", "domain:smokershub.com",
        "keyword:firearm", "keyword:ammo", "keyword:holster",
        "keyword:for sale", "keyword:buy online", "keyword:discount",
    ],
    "Entertainment & Streaming": [
        # Video Streaming
        "domain:youtube.com", "domain:youtu.be", "domain:music.youtube.com",
        "domain:netflix.com", "domain:hulu.com", "domain:disneyplus.com",
        "domain:hbomax.com", "domain:max.com", "domain:primevideo.com",
        "domain:peacocktv.com", "domain:paramountplus.com",
        "domain:pluto.tv", "domain:tubi.tv", "domain:crackle.com",
        "domain:vudu.com", "domain:dailymotion.com", "domain:vimeo.com",
        # Live Streaming
        "domain:twitch.tv", "domain:kick.com", "domain:rumble.com",
        "domain:fishtank.live", "domain:dlive.tv", "domain:trovo.live",
        "domain:bitwave.tv", "domain:censored.tv", "domain:cozy.tv",
        "domain:bitchute.com", "domain:odysee.com", "domain:liveomg.com",
        "domain:putchannel.com", "domain:patreon.com",
        # Movies & TV
        "domain:imdb.com", "domain:rottentomatoes.com", "domain:letterboxd.com",
        "domain:justwatch.com", "domain:thetvdb.com", "domain:themoviedb.org",
        "domain:trakt.tv", "domain:abetterqueue.com",
        "domain:arc018.to", "domain:flixmomo.com",
        "domain:uflix.to", "domain:thetvapp.to",
        "domain:noodlemagazine.com", "domain:leonardaisfunny.com",
        "domain:metiix.com", "domain:godownloads.net",
        "domain:solarmoviez.ru", "domain:m4uhd.page",
        "domain:publiciptv.com", "domain:streamlicensing.com",
        "domain:stream2video.tv", "domain:usnewslive.tv",
        "domain:mysuncoast.com", "domain:southhemitv.com",
        "domain:americafirst.live", "domain:unauthorized.tv",
        "domain:banned.video", "domain:warroom.org", "domain:pandemic.warroom.org",
        "domain:ome.tv", "domain:chaturbate.com",
        # Professional streaming infrastructure
        "domain:dacast.com", "domain:brightcove.com", "domain:vimeo.com",
        "domain:storyblocks.com",
        "domain:myslingstudio.com", "domain:gatesair.com",
        "domain:kapwing.com", "domain:heroturko.me",
        "domain:downr.org", "domain:audfree.com",
        "domain:desktop.captions.ai", "domain:captions.ai",
        # Music & Audio
        "domain:spotify.com", "domain:open.spotify.com",
        "domain:soundcloud.com", "domain:bandcamp.com",
        "domain:last.fm", "domain:deezer.com", "domain:tidal.com",
        "domain:music.apple.com", "domain:distrokid.com",
        "domain:tothebestof.com", "domain:genius.com",
        "domain:tunetidy.com", "domain:cduniverse.com",
        "domain:crunchyroll.com",
        "domain:pandora.com", "domain:stereomood.com", "domain:relaxingbeats.com",
        "domain:artists.apple.com", "domain:getcoverify.com",
        "domain:getworkdonemusic.com", "domain:bensound.com",
        "domain:groovedrumming.com", "domain:myinstants.com",
        "domain:bertcast.com", "domain:toao.net",
        "domain:itunes.apple.com",
        # Music production / royalty-free
        "domain:looperman.com", "domain:splice.com",
        "domain:beatstars.com", "domain:freesound.org",
        "keyword:asmr", "keyword:playlist", "keyword:instrumental",
    ],
    "Gaming": [
        "domain:steam.com", "domain:steampowered.com", "domain:store.steampowered.com",
        "domain:epicgames.com", "domain:gog.com", "domain:itch.io",
        "domain:xbox.com", "domain:playstation.com", "domain:nintendo.com",
        "domain:ign.com", "domain:gamespot.com", "domain:pcgamer.com",
        "domain:kotaku.com", "domain:polygon.com",
        "domain:curseforge.com", "domain:modrinth.com", "domain:minecraft.net",
        "domain:mcprohosting.com", "domain:dev.bukkit.org",
        "domain:roblox.com", "domain:ea.com", "domain:ubisoft.com",
        "domain:crusaders.gg", "domain:battlefy.com",
        "domain:ea.sports", "domain:leagueoflegends.com",
        "domain:riotgames.com", "domain:blizzard.com",
        "domain:battle.net", "domain:bethesda.net",
        "domain:humblebundle.com", "domain:fanatical.com",
        "domain:gamivo.com", "domain:cdkeys.com", "domain:g2a.com",
        "domain:speedrun.com", "domain:twitchmetrics.net",
        "domain:howlongtobeat.com", "domain:backloggd.com",
    ],
    "Finance & Banking": [
        "domain:chase.com", "domain:bankofamerica.com", "domain:wellsfargo.com",
        "domain:paypal.com", "domain:venmo.com", "domain:robinhood.com",
        "domain:fidelity.com", "domain:coinbase.com", "domain:mint.com",
        "domain:creditkarma.com", "domain:turbotax.com",
        "domain:irs.gov", "domain:stripe.com", "domain:square.com",
        "domain:quickbooks.intuit.com", "domain:freshbooks.com",
        "domain:gusto.com", "domain:paylocity.com",
        # Credit unions / regional banks
        "domain:wpcuonline.net", "domain:wpcu.coop",
        "domain:achievacu.com", "domain:banking.achievacu.com",
        "domain:creditonebank.com", "domain:auth.tiaa.org", "domain:tiaa.org",
        "domain:suncoastcreditunion.com",
        "domain:pnc.com", "domain:usbank.com", "domain:citibank.com",
        "domain:capitalone.com", "domain:discover.com",
        "domain:ally.com", "domain:schwab.com", "domain:vanguard.com",
        "domain:kraken.com", "domain:binance.com", "domain:gemini.com",
        # Insurance (finance-adjacent)
        "domain:ecams.geico.com", "domain:geico.com",
        "domain:progressive.com", "domain:statefarm.com",
        "domain:allstate.com", "domain:usaa.com",
        "domain:manage.myassurantpolicy.com", "domain:assurant.com",
        # Crypto / stocks / finance data
        "domain:bitbo.io", "domain:coinmarketcap.com", "domain:coingecko.com",
        "domain:etherscan.io", "domain:blockchain.com",
        "domain:finviz.com", "domain:yahoo.com/finance",
        "domain:marketwatch.com", "domain:cnbc.com",
        "domain:nasdaq.com", "domain:seekingalpha.com",
        "domain:morningstar.com", "domain:investing.com",
        "keyword:credit union", "keyword:banking", "keyword:online banking",
        "keyword:brokerage", "keyword:investment", "keyword:insurance",
        "keyword:bitcoin price", "keyword:crypto", "keyword:ethereum",
        "keyword:stock price", "keyword:commodities", "keyword:oil price",
    ],
    "Education & Learning": [
        "domain:coursera.org", "domain:udemy.com", "domain:edx.org",
        "domain:khanacademy.org", "domain:udacity.com", "domain:codecademy.com",
        "domain:freecodecamp.org", "domain:duolingo.com", "domain:masterclass.com",
        "domain:pluralsight.com", "domain:skillshare.com", "domain:lynda.com",
        "domain:flatiron.com",
        "keyword:certification", "keyword:practice test",
        "keyword:comptia", "keyword:microsoft cert"
    ],
    "Reference & Research": [
        "domain:wikipedia.org", "domain:en.wikipedia.org", "domain:britannica.com",
        "domain:merriam-webster.com", "domain:dictionary.com",
        "domain:scholar.google.com", "domain:arxiv.org", "domain:pubmed.gov",
        "domain:wolframalpha.com", "domain:archive.org", "domain:web.archive.org",
        "domain:biblegateway.com", "domain:quora.com",
        # Flight & Ship Tracking
        "domain:globe.airplanes.live", "domain:globe.adsbexchange.com",
        "domain:flightradar24.com", "domain:flightaware.com",
        "domain:planefinder.net", "domain:marinetraffic.com",
        "domain:vesselfinder.com",
        # Maps & Geo
        "domain:maps.google.com", "domain:openstreetmap.org",
        "domain:earth.google.com", "domain:darksitefinder.com",
        "domain:justicemap.org",
        "domain:arcgis.com", "domain:apps.sentinel-hub.com", "domain:sentinel-hub.com",
        "domain:mapautist.com", "domain:nuclearsecrecy.com",
        # Search engines
        "domain:duckduckgo.com", "domain:start.me",
        "domain:translate.google.com",
        "domain:startpage.com", "domain:kagi.com", "domain:brave.com",
        "domain:yandex.com", "domain:baidu.com",
        "domain:search.brave.com", "domain:qwant.com",
        "domain:ecosia.org", "domain:searxng.org",
        # Reference / encyclopedic
        "domain:infogalactic.com", "domain:wiktionary.org",
        "domain:thefreedictionary.com", "domain:vocabulary.com",
        "domain:snopes.com", "domain:factcheck.org",
        "domain:politifact.com", "domain:straightdope.com",
        "domain:tineye.com",  # reverse image search
        # User's generic Google account / profile
        "domain:myaccount.google.com", "domain:accounts.google.com",
    ],
    "Travel & Transportation": [
        "domain:booking.com", "domain:airbnb.com", "domain:expedia.com",
        "domain:kayak.com", "domain:tripadvisor.com", "domain:vrbo.com",
        "domain:hotels.com", "domain:hotwire.com", "domain:priceline.com",
        "domain:travelocity.com", "domain:orbitz.com",
        "domain:uber.com", "domain:lyft.com", "domain:skyscanner.com",
        "domain:southwest.com", "domain:united.com", "domain:delta.com",
        "domain:aa.com", "domain:allegiantair.com", "domain:spiritairlines.com",
        "domain:amtrak.com", "domain:greyhound.com",
        # Local / municipal (Florida / Ohio per user profile)
        "domain:venicegov.com", "domain:downtowndayton.org",
        "domain:fpl.com", "domain:duke-energy.com",
        # Additional travel
        "domain:hopper.com", "domain:trivago.com",
        "domain:ihg.com", "domain:marriott.com", "domain:hilton.com",
        "domain:hyatt.com", "domain:choicehotels.com",
        "domain:momondo.com", "domain:google.com/flights",
        "keyword:flights to", "keyword:hotel booking",
    ],
    "Food & Dining": [
        "domain:doordash.com", "domain:ubereats.com", "domain:grubhub.com",
        "domain:instacart.com", "domain:yelp.com", "domain:opentable.com",
        "domain:allrecipes.com", "domain:epicurious.com",
        "keyword:recipe", "keyword:restaurant", "keyword:cooking"
    ],
    "Health & Medical": [
        "domain:webmd.com", "domain:mayoclinic.org", "domain:healthline.com",
        "domain:nih.gov", "domain:cdc.gov", "domain:who.int",
        "domain:drugs.com", "domain:zocdoc.com", "domain:goodrx.com",
        "domain:rxlist.com", "domain:medlineplus.gov",
        "domain:myfitnesspal.com", "domain:strava.com",
        "domain:cernerhealth.com", "domain:mychart.com",
        "domain:myhealthrecord.com", "domain:clevelandclinic.org",
        "domain:medicatechusa.com",
        # Medical imaging / PACS (user's domain)
        "domain:mavenimaging.com", "domain:support.mavenimaging.com",
        "domain:2020imaging.net",
        "domain:member.compassphs.com", "domain:compassphs.com",
        "domain:covid19criticalcare.com",
        # Additional patient portals / insurance
        "domain:anthem.com", "domain:mymoffitt.org",
        "domain:mychart.premierhealthpartners.org",
        "domain:premierhealthpartners.org",
        "domain:pullpush.io",
        # Pharmacies (online)
        "domain:modafinilxl.com", "domain:modafinilusa.com",
        "domain:alldaychemist.com", "domain:liherbals.com",
        # Tattoo / body modification
        "domain:inkdrop.co", "domain:tattoo.com",
        # General health
        "domain:medscape.com", "domain:mercola.com",
        "domain:manage.myassurantpolicy.com",
        # DICOM viewers / imaging tools
        "domain:weasis.org", "domain:osirix-viewer.com",
        "domain:radiantviewer.com", "domain:horosproject.org",
        "domain:mangosoftware.com",
        "domain:views.paperflite.com", "domain:paperflite.com",
        "keyword:dicom", "keyword:pacs", "keyword:x-ray", "keyword:radiology",
        "keyword:patient portal", "keyword:mychart", "keyword:imaging",
        "keyword:medical record", "keyword:prescription",
    ],
    "Job Search & Career": [
        "domain:indeed.com", "domain:glassdoor.com", "domain:monster.com",
        "domain:ziprecruiter.com", "domain:dice.com", "domain:simplyhired.com",
        "domain:careerbuilder.com", "domain:roberthalf.com",
        "domain:upwork.com", "domain:fiverr.com", "domain:freelancer.com",
        "domain:governmentjobs.com", "domain:care.com",
        "domain:kellyservices.us", "domain:tbe.taleo.net",
        "domain:remoteok.com", "domain:levels.fyi",
        "domain:linkedin.com/jobs",
        "domain:jobs.net", "domain:careerplug.com",
        "domain:kellycareernetwork.tms.hrdepartment.com",
        "domain:tms.hrdepartment.com", "domain:hrdepartment.com",
        "domain:teamlogic-it-careers.careerplug.com",
        "domain:careers.suncoastcreditunion.com",
        "domain:workday.com", "domain:myworkday.com",
        "domain:greenhouse.io", "domain:lever.co",
        "domain:smartrecruiters.com", "domain:jobvite.com",
        "domain:bamboohr.com",
        "domain:angel.co", "domain:wellfound.com", "domain:hired.com",
        "domain:flexjobs.com", "domain:workingnomads.co",
        "domain:weworkremotely.com", "domain:remote.co",
        # Career / freelance platforms
        "domain:toptal.com", "domain:guru.com", "domain:99designs.com",
        # Subdomain patterns for company career pages
        "keyword:careers.", "keyword:jobs.",
        "keyword:job opening", "keyword:careers at", "keyword:staffing",
        "keyword:resume", "keyword:hiring", "keyword:recruiter",
        "keyword:interview", "keyword:salary",
    ],
    "Real Estate": [
        "domain:zillow.com", "domain:realtor.com", "domain:redfin.com",
        "domain:trulia.com", "domain:apartments.com", "domain:rent.com",
        "domain:rocketmortgage.com", "domain:appfolio.com",
        "domain:hotpads.com", "domain:compassmgmt.appfolio.com",
        "domain:forrent.com", "domain:rentcafe.com",
        "domain:auction.com", "domain:homes.com", "domain:loopnet.com",
        "domain:costar.com", "domain:landwatch.com",
        "domain:padmapper.com", "domain:streeteasy.com",
        "keyword:real estate", "keyword:for rent", "keyword:apartment",
        "keyword:condo for", "keyword:house for", "keyword:mortgage",
        "keyword:home value", "keyword:zestimate",
    ],
    "Automotive": [
        "domain:cars.com", "domain:autotrader.com", "domain:cargurus.com",
        "domain:carmax.com", "domain:kbb.com", "domain:edmunds.com",
        "domain:truecar.com", "domain:vroom.com", "domain:carvana.com"
    ],
    "Sports": [
        "domain:espn.com", "domain:sports.yahoo.com", "domain:bleacherreport.com",
        "domain:nba.com", "domain:nfl.com", "domain:mlb.com", "domain:nhl.com",
        "domain:cbssports.com", "domain:foxsports.com", "domain:theathletic.com"
    ],
    "Government & Legal": [
        "regex:\\.gov(/|$)", "domain:usa.gov", "domain:irs.gov", "domain:ssa.gov",
        "domain:cms.gov", "domain:sec.gov", "domain:fda.gov",
        "domain:fcc.gov", "domain:ftc.gov",
        "domain:law.cornell.edu", "domain:findlaw.com",
        "domain:sunbiz.org", "domain:search.sunbiz.org",
        "domain:myflorida.com", "domain:flhsmv.gov", "domain:floridajobs.org",
        "domain:mydmvportal-flhsmv.my.site.com",
        # Additional legal/court
        "domain:pacer.gov", "domain:uscourts.gov",
        "domain:justia.com", "domain:nolo.com", "domain:rocketlawyer.com",
        "domain:legalzoom.com", "domain:avvo.com",
        # International
        "domain:gov.uk", "domain:canada.ca", "domain:gov.au",
    ],
    "Downloads & Torrents": [
        "domain:1337x.to", "domain:thepiratebay.org", "domain:rarbg.to",
        "domain:nyaa.si", "domain:fitgirl-repacks.site",
        "domain:thehouseofportable.com", "domain:filecr.com",
        "domain:rutracker.org", "domain:thegeeks.bz", "domain:torrentgalaxy.to",
        "domain:yts.mx", "domain:eztv.re", "domain:limetorrents.info",
        "domain:forum.mobilism.me", "domain:mobilism.me",
        "domain:mega.nz", "domain:mediafire.com", "domain:file-upload.org",
        "domain:fcportables.com",
        # Piracy indexes / releases
        "domain:fmhy.net", "domain:lookmovie2.to", "domain:kickass.to",
        "domain:palined.com", "domain:filepursuit.com", "domain:usersdrive.com",
        "domain:predb.net", "domain:redact.dev",
        "domain:w16.monkrus.ws", "domain:monkrus.ws",
        "domain:couchtuner.show", "domain:shrimpstreams.live",
        "domain:cnvmp3.com",
        # File hosts
        "domain:filenext.com", "domain:katfile.com", "domain:rapidgator.net",
        "domain:uploadgig.com", "domain:nitroflare.com", "domain:keep2share.cc",
        # DDL archives
        "domain:softarchive.is", "domain:downloadly.ir",
        "domain:getintopc.com", "domain:igg-games.com",
        "domain:ocean-of-games.com", "domain:oceanofgames.com",
        "domain:skidrowreloaded.com", "domain:skidrow-games.com",
        "keyword:torrent", "keyword:magnet", "keyword:seedbox",
        "keyword:nulled", "keyword:crack", "keyword:warez",
        "keyword:free download", "keyword:direct download",
        "keyword:scene release",
    ],
    "Media Production & Design": [
        # Video Equipment
        "domain:teradek.com", "domain:blackmagicdesign.com",
        "domain:obsproject.com", "domain:sbe.org",
        # Graphics & Templates
        "domain:gfxtra.com", "domain:gfxdrug.com", "domain:gfxdownload.com",
        "domain:intro-hd.net", "domain:freepreset.net", "domain:freevideoeffect.com",
        "domain:motionarray.com", "domain:envato.com", "domain:elements.envato.com",
        "domain:prodesigntools.com", "domain:helpx.adobe.com", "domain:adobe.com",
        "domain:creativecloud.adobe.com",
        # Stock Media
        "domain:pexels.com", "domain:unsplash.com", "domain:pixabay.com",
        "domain:shutterstock.com", "domain:gettyimages.com",
        "domain:videvo.net", "domain:artlist.io",
        # Design Tools
        "domain:dribbble.com", "domain:behance.net", "domain:99designs.com",
        "domain:brandcrowd.com", "domain:looka.com",
        "domain:freepik.com", "domain:flaticon.com", "domain:iconmonstr.com",
        "domain:icons8.com", "domain:fontawesome.com",
        "domain:dafont.com", "domain:fontsquirrel.com",
        "domain:pngwing.com", "domain:canva.com", "domain:figma.com",
        # GFX / VFX repositories
        "domain:gfxtra31.com",
        "domain:vfxdownload.net", "domain:psdflyer.co", "domain:nitrogfx.pro",
        "domain:free-psd-templates.com", "domain:scriptmafia.org",
        "domain:graphicriver.net", "domain:videohive.net",
        "domain:templatemonster.com", "domain:themeforest.net",
        "domain:awesomeflyer.com", "domain:ae-share.com", "domain:ae-project.su",
        # UI / animation tools
        "domain:loading.io", "domain:lottiefiles.com",
        "domain:keyshape.app", "domain:vectr.com",
        # Audio / video editing
        "domain:audiojungle.net", "domain:soundsnap.com",
        "domain:producerspot.com",
        "keyword:after effects", "keyword:premiere pro", "keyword:stock footage",
        "keyword:videohive", "keyword:motion graphic",
        "keyword:psd template", "keyword:photoshop template",
        "keyword:vfx", "keyword:cinema 4d", "keyword:blender",
    ],
    "Software & Customization": [
        # Windows Themes
        "domain:vsthemes.org", "domain:deviantart.com", "domain:windhawk.net",
        "domain:startallback.com", "domain:stardock.com", "domain:rainmeter.net",
        "keyword:theme", "keyword:wallpaper", "keyword:dark mode",
        # Applications
        "domain:ninite.com", "domain:portableapps.com", "domain:portablefreeware.com",
        "domain:majorgeeks.com", "domain:softpedia.com", "domain:filehippo.com",
        "domain:alternativeto.net", "domain:wingetgui.com",
        "domain:voidtools.com", "domain:freewaregenius.com",
        "domain:mozilla.org", "domain:mozilla.com",
        "domain:7-zip.org", "domain:notepad-plus-plus.org",
        "domain:videolan.org", "domain:handbrake.fr", "domain:audacity.org",
        "domain:gimp.org", "domain:inkscape.org", "domain:libreoffice.org",
        # More popular apps
        "domain:obsidian.md", "domain:logseq.com", "domain:anytype.io",
        "domain:zotero.org", "domain:calibre-ebook.com",
        "domain:keepass.info", "domain:keepassxc.org",
        "domain:veracrypt.fr", "domain:truecrypt.ch",
        "domain:everything.voidtools.com",
        "domain:fastcopy.jp", "domain:teracopy.com",
    ],
    "Productivity & Tools": [
        # Google Workspace
        "domain:docs.google.com", "domain:drive.google.com",
        "domain:sheets.google.com", "domain:slides.google.com",
        "domain:keep.google.com", "domain:calendar.google.com",
        "domain:sites.google.com", "domain:photos.google.com",
        "domain:fonts.google.com",
        # Email & Communication
        "domain:mail.google.com", "domain:outlook.live.com",
        "domain:outlook.office.com", "domain:login.live.com",
        "domain:mail.yahoo.com", "domain:messages.google.com",
        "domain:aol.com", "domain:mail.com", "domain:fastmail.com",
        "domain:tuta.io", "domain:tutanota.com",
        # Online Tools
        "domain:notion.so", "domain:trello.com", "domain:asana.com",
        "domain:airtable.com", "domain:feedly.com",
        "domain:iloveimg.com", "domain:ilovepdf.com", "domain:ezgif.com",
        "domain:cloudconvert.com",
        "domain:hubspot.com",
        # Cloud storage (user-facing productivity)
        "domain:dropbox.com", "domain:onedrive.live.com", "domain:onedrive.com",
        "domain:box.com", "domain:sync.com", "domain:pcloud.com",
        # Other productivity
        "domain:tunemymusic.com",  # music playlist tool
        "domain:toggl.com", "domain:harvestapp.com",
        "domain:clockify.me", "domain:rescuetime.com",
        "domain:evernote.com", "domain:onenote.com",
        "domain:monday.com", "domain:clickup.com", "domain:basecamp.com",
        "domain:miro.com", "domain:mural.co", "domain:lucidchart.com",
        "domain:draw.io", "domain:app.diagrams.net",
        # Calendar / scheduling
        "domain:calendly.com", "domain:doodle.com",
        # Password managers (primary utility for many)
        "domain:1password.com", "domain:dashlane.com",
        # Google.com catch-all (last fallback for generic searches/accounts).
        # Keep at the very end so specific subdomain rules in other
        # categories (News, AI, Cloud, Reference) match first.
        "domain:google.com",
    ],
}

